# Pipeline MLCQ — Visão geral dos dados

Este notebook resume o fluxo: **CSV original** → **busca do código nos repositórios** → **CSV com snippets** → **geração de SQL para a base**.

## 1. CSV original

Carregamento e visão geral do dataset original (metadados: repo, commit, path, start_line, end_line — **sem trecho de código**).

In [29]:
from pathlib import Path
import pandas as pd

BASE = Path.cwd().resolve()
original = pd.read_csv(BASE / "mlcq_original_dataset.csv", sep=";")
original.head()

,id,reviewer_id,sample_id,smell,severity,review_timestamp,type,code_name,repository,commit_hash,path,start_line,end_line,link,is_from_industry_relevant_project
0,526,6,5771277,feature envy,none,2019-03-27 10:34:53.041496,function,org.apache.syncope.client.ui.commons.ConnIdSpe...,git@github.com:apache/syncope.git,114c412afbfba24ffb4fbc804e5308a823a16a78,/client/idrepo/ui/src/main/java/org/apache/syn...,35,37,https://github.com/apache/syncope/blob/114c412...,1
1,527,6,5771277,long method,none,2019-03-27 10:34:53.042443,function,org.apache.syncope.client.ui.commons.ConnIdSpe...,git@github.com:apache/syncope.git,114c412afbfba24ffb4fbc804e5308a823a16a78,/client/idrepo/ui/src/main/java/org/apache/syn...,35,37,https://github.com/apache/syncope/blob/114c412...,1
2,528,6,5786929,blob,critical,2019-03-27 10:37:38.107923,class,org.apache.tez.runtime.library.common.writers....,git@github.com:apache/tez.git,d5675c332497c1ac1dedefdf91e87476b5c0d7a9,/tez-runtime-library/src/main/java/org/apache/...,89,1427,https://github.com/apache/tez/blob/d5675c33249...,1
3,529,6,5786929,data class,critical,2019-03-27 10:37:38.109068,class,org.apache.tez.runtime.library.common.writers....,git@github.com:apache/tez.git,d5675c332497c1ac1dedefdf91e87476b5c0d7a9,/tez-runtime-library/src/main/java/org/apache/...,89,1427,https://github.com/apache/tez/blob/d5675c33249...,1
4,530,6,5788107,feature envy,none,2019-03-27 10:37:49.627100,function,org.apache.tika.parser.ocr.TesseractOCRConfig#...,git@github.com:apache/tika.git,4131c6e30f2e0eb1feb85e0f7576531d4e830468,/tika-parsers/src/main/java/org/apache/tika/pa...,531,534,https://github.com/apache/tika/blob/4131c6e30f...,1

*Pre-processing of dataset*

In [30]:
# Filter by relevant projects and copy dataset to perfom changes
original = original[original['is_from_industry_relevant_project'] == '1'].copy()
# Convert lines to numeric where suitable
original['start_line'] = pd.to_numeric(original['start_line'], errors='coerce')
original['end_line'] = pd.to_numeric(original['end_line'], errors='coerce')
original = original.dropna(subset=['start_line', 'end_line'])
original['start_line'] = original['start_line'].astype(int)
original['end_line'] = original['end_line'].astype(int)
# remove lines with empty core data 
original = original.dropna(subset=['repository', 'commit_hash', 'path'])

In [31]:
original.shape

(12710, 15)

## 2. Busca do código nos repositórios

O dataset **não traz o code snippet**, apenas as indicações (repositório, commit, arquivo, `start_line`, `end_line`). Por isso foi necessário buscar o conteúdo nos repositórios. O script `collect_mlcq_samples_with_source_code.py` faz essa coleta via API do GitHub e gera um CSV com os campos originais mais `code_snippet` e `file_content`.

In [ ]:
# Dataset já salvo; descomente abaixo para refazer a busca do source code nos repositórios
# original.to_csv(BASE / "mlcq_filtered_dataset.csv", sep=";", index=False)
#
# import sys
# sys.path.insert(0, str(BASE))
# from collect_mlcq_samples_with_source_code import process_dataset
#
# process_dataset(
#     original_csv_file=str(BASE / "mlcq_filtered_dataset.csv"),
#     json_file=str(BASE / "original_mlcq_samples.json"),
#     csv_file_with_source_code=str(BASE / "mlcq_enriched_dataset.csv"),
# )

Fetching code + source files: 25it [00:06,  4.15it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/action/TrimAction.java (status: 404)
Warning: Failed to fetch file for ID 550
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/action/TrimAction.java (status: 404)
Warning: Failed to fetch file for ID 551

Fetching code + source files: 36it [00:08,  4.63it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/cde/ui/DocumentTableLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 560
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/cde/ui/DocumentTableLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 561

Fetching code + source files: 50it [00:12,  4.67it/s]

Saved batch of 46 entries.

Fetching code + source files: 68it [00:16,  4.91it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/webservices-xmlschema/f189e891c88298f52f92cfe8f24dccb809e05607/xmlschema-core/src/main/java/org/apache/ws/commons/schema/XmlSchemaChoiceMember.java (status: 404)
Warning: Failed to fetch file for ID 594
Failed to fetch file: https://raw.githubusercontent.com/apache/webservices-xmlschema/f189e891c88298f52f92cfe8f24dccb809e05607/xmlschema-core/src/main/java/org/apache/ws/commons/schema/XmlSchemaChoiceMember.java (status: 404)
Warning: Failed to fetch file for ID 595

Fetching code + source files: 90it [00:21,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust13.java (status: 404)
Warning: Failed to fetch file for ID 626
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust13.java (status: 404)
Warning: Failed to fetch file for ID 627

Fetching code + source files: 93it [00:22,  5.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust10.java (status: 404)
Warning: Failed to fetch file for ID 628
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust10.java (status: 404)
Warning: Failed to fetch file for ID 629

Fetching code + source files: 94it [00:22,  4.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/ui refactoring/org/eclipse/dltk/internal/ui/refactoring/reorg/RenameRefactoringWizard.java (status: 404)
Warning: Failed to fetch file for ID 630
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/ui refactoring/org/eclipse/dltk/internal/ui/refactoring/reorg/RenameRefactoringWizard.java (status: 404)
Warning: Failed to fetch file for ID 631

Fetching code + source files: 96it [00:23,  4.88it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 632
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 633

Fetching code + source files: 100it [00:23,  4.72it/s]

Saved batch of 40 entries.

Fetching code + source files: 108it [00:25,  4.71it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/preferences/dialogs/CreateStepFilterDialog.java (status: 404)
Warning: Failed to fetch file for ID 646
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/preferences/dialogs/CreateStepFilterDialog.java (status: 404)
Warning: Failed to fetch file for ID 647

Fetching code + source files: 126it [00:29,  3.95it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui.test/src/org/eclipse/egit/ui/common/SharingWizard.java (status: 404)
Warning: Failed to fetch file for ID 664
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui.test/src/org/eclipse/egit/ui/common/SharingWizard.java (status: 404)
Warning: Failed to fetch file for ID 665

Fetching code + source files: 144it [00:33,  4.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/synchronize/action/ExpandAllModelAction.java (status: 404)
Warning: Failed to fetch file for ID 684
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/synchronize/action/ExpandAllModelAction.java (status: 404)
Warning: Failed to fetch file for ID 685

Fetching code + source files: 150it [00:35,  4.36it/s]

Saved batch of 44 entries.

Fetching code + source files: 195it [00:46,  4.93it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/internal/transport/sshd/JGitHostConfigEntry.java (status: 404)
Warning: Failed to fetch file for ID 734
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/internal/transport/sshd/JGitHostConfigEntry.java (status: 404)
Warning: Failed to fetch file for ID 735

Fetching code + source files: 200it [00:47,  4.15it/s]

Saved batch of 48 entries.

Fetching code + source files: 228it [00:54,  3.95it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 770
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 771

Fetching code + source files: 230it [00:54,  4.39it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/ChooseWorkspaceData.java (status: 404)
Warning: Failed to fetch file for ID 774
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/ChooseWorkspaceData.java (status: 404)
Warning: Failed to fetch file for ID 775

Fetching code + source files: 234it [00:55,  4.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/window/IShellProvider.java (status: 404)
Warning: Failed to fetch file for ID 780
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/window/IShellProvider.java (status: 404)
Warning: Failed to fetch file for ID 781

Fetching code + source files: 238it [00:56,  4.46it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core.test/src/org/eclipse/nebula/widgets/nattable/viewport/ViewportLayerTest2.java (status: 404)
Warning: Failed to fetch file for ID 784
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core.test/src/org/eclipse/nebula/widgets/nattable/viewport/ViewportLayerTest2.java (status: 404)
Warning: Failed to fetch file for ID 785

Fetching code + source files: 241it [00:56,  5.25it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 786
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 787

Fetching code + source files: 242it [00:56,  4.56it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.navigator/src/org/eclipse/ui/internal/navigator/VisibilityAssistant.java (status: 404)
Warning: Failed to fetch file for ID 788
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.navigator/src/org/eclipse/ui/internal/navigator/VisibilityAssistant.java (status: 404)
Warning: Failed to fetch file for ID 789

Fetching code + source files: 244it [00:57,  4.69it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/dialogs/UIMessageDialogs.java (status: 404)
Warning: Failed to fetch file for ID 790
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/dialogs/UIMessageDialogs.java (status: 404)
Warning: Failed to fetch file for ID 791

Fetching code + source files: 246it [00:57,  4.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.launching/src/org/eclipse/m2e/ui/internal/launch/MavenLaunchMainTab.java (status: 404)
Warning: Failed to fetch file for ID 792
Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.launching/src/org/eclipse/m2e/ui/internal/launch/MavenLaunchMainTab.java (status: 404)
Warning: Failed to fetch file for ID 793

Fetching code + source files: 250it [00:58,  4.41it/s]

Saved batch of 34 entries.

Fetching code + source files: 253it [00:59,  5.02it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.navigator/src/org/eclipse/ui/internal/navigator/sorters/SkeletonViewerSorter.java (status: 404)
Warning: Failed to fetch file for ID 798
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.navigator/src/org/eclipse/ui/internal/navigator/sorters/SkeletonViewerSorter.java (status: 404)
Warning: Failed to fetch file for ID 799

Fetching code + source files: 256it [00:59,  4.61it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface.databinding/src/org/eclipse/jface/databinding/viewers/ObservableSetTreeContentProvider.java (status: 404)
Warning: Failed to fetch file for ID 802
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface.databinding/src/org/eclipse/jface/databinding/viewers/ObservableSetTreeContentProvider.java (status: 404)
Warning: Failed to fetch file for ID 803

Fetching code + source files: 260it [01:00,  4.61it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/themes/ThemeElementDefinition.java (status: 404)
Warning: Failed to fetch file for ID 806
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/themes/ThemeElementDefinition.java (status: 404)
Warning: Failed to fetch file for ID 807

Fetching code + source files: 278it [01:04,  5.00it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 824
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 825

Fetching code + source files: 282it [01:05,  4.67it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/handlers/ShowViewHandler.java (status: 404)
Warning: Failed to fetch file for ID 828
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/handlers/ShowViewHandler.java (status: 404)
Warning: Failed to fetch file for ID 829

Fetching code + source files: 300it [01:10,  3.68it/s]

Saved batch of 40 entries.

Fetching code + source files: 332it [01:18,  2.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java (status: 404)
Warning: Failed to fetch file for ID 880
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java (status: 404)
Warning: Failed to fetch file for ID 881

Fetching code + source files: 344it [01:21,  4.05it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/ConnectionMessages.java (status: 404)
Warning: Failed to fetch file for ID 892
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/ConnectionMessages.java (status: 404)
Warning: Failed to fetch file for ID 893

Fetching code + source files: 350it [01:23,  4.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/widgets/treeitemkit/TreeItemLCA.java (status: 404)
Warning: Failed to fetch file for ID 898
Saved batch of 45 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/widgets/treeitemkit/TreeItemLCA.java (status: 404)
Warning: Failed to fetch file for ID 899

Fetching code + source files: 352it [01:23,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.views/src/org/eclipse/ui/views/properties/ComboBoxPropertyDescriptor.java (status: 404)
Warning: Failed to fetch file for ID 900
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.views/src/org/eclipse/ui/views/properties/ComboBoxPropertyDescriptor.java (status: 404)
Warning: Failed to fetch file for ID 901

Fetching code + source files: 355it [01:24,  4.80it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/Menu.java (status: 404)
Warning: Failed to fetch file for ID 902
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/Menu.java (status: 404)
Warning: Failed to fetch file for ID 903

Fetching code + source files: 356it [01:24,  4.50it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/AbstractIntegerListener.java (status: 404)
Warning: Failed to fetch file for ID 904
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/AbstractIntegerListener.java (status: 404)
Warning: Failed to fetch file for ID 905

Fetching code + source files: 358it [01:24,  4.85it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/theme/css/NullElementSelector.java (status: 404)
Warning: Failed to fetch file for ID 906
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/theme/css/NullElementSelector.java (status: 404)
Warning: Failed to fetch file for ID 907

Fetching code + source files: 361it [01:25,  5.51it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.jface.databinding/src/org/eclipse/jface/databinding/viewers/ObservableMapCellLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 908
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.jface.databinding/src/org/eclipse/jface/databinding/viewers/ObservableMapCellLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 909

Fetching code + source files: 362it [01:25,  4.99it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/WebClientProvider.java (status: 404)
Warning: Failed to fetch file for ID 910
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/WebClientProvider.java (status: 404)
Warning: Failed to fetch file for ID 911

Fetching code + source files: 364it [01:26,  4.85it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/decorators/DecoratorRegistryReader.java (status: 404)
Warning: Failed to fetch file for ID 912
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/decorators/DecoratorRegistryReader.java (status: 404)
Warning: Failed to fetch file for ID 913

Fetching code + source files: 367it [01:26,  5.40it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/css/org/eclipse/rap/rwt/apache/batik/util/io/ASCIIDecoder.java (status: 404)
Warning: Failed to fetch file for ID 914
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/css/org/eclipse/rap/rwt/apache/batik/util/io/ASCIIDecoder.java (status: 404)
Warning: Failed to fetch file for ID 915

Fetching code + source files: 369it [01:26,  5.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/tests/org.eclipse.rap.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/decorators/DecoratorEnablementTestCase.java (status: 404)
Warning: Failed to fetch file for ID 916
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/tests/org.eclipse.rap.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/decorators/DecoratorEnablementTestCase.java (status: 404)
Warning: Failed to fetch file for ID 917

Fetching code + source files: 370it [01:27,  4.91it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/PageLayout.java (status: 404)
Warning: Failed to fetch file for ID 918
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/PageLayout.java (status: 404)
Warning: Failed to fetch file for ID 919

Fetching code + source files: 373it [01:27,  5.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/custom/SashFormLayout.java (status: 404)
Warning: Failed to fetch file for ID 922
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/custom/SashFormLayout.java (status: 404)
Warning: Failed to fetch file for ID 923

Fetching code + source files: 374it [01:28,  4.46it/s]

Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-model/src/main/java/com/epam/dlab/util/CloudSettingsDeserializer.java (status: 404)
Warning: Failed to fetch file for ID 924
Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-model/src/main/java/com/epam/dlab/util/CloudSettingsDeserializer.java (status: 404)
Warning: Failed to fetch file for ID 925

Fetching code + source files: 376it [01:28,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-auth-common/src/main/java/com/epam/dlab/auth/SecurityUnauthorizedHandler.java (status: 404)
Warning: Failed to fetch file for ID 926
Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-auth-common/src/main/java/com/epam/dlab/auth/SecurityUnauthorizedHandler.java (status: 404)
Warning: Failed to fetch file for ID 927

Fetching code + source files: 378it [01:28,  4.86it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/AbstractPartSelectionTracker.java (status: 404)
Warning: Failed to fetch file for ID 928
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/AbstractPartSelectionTracker.java (status: 404)
Warning: Failed to fetch file for ID 929

Fetching code + source files: 381it [01:29,  5.20it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IPluginContribution.java (status: 404)
Warning: Failed to fetch file for ID 930
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IPluginContribution.java (status: 404)
Warning: Failed to fetch file for ID 931

Fetching code + source files: 396it [01:32,  4.65it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/progress/AnimationManager.java (status: 404)
Warning: Failed to fetch file for ID 950
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/progress/AnimationManager.java (status: 404)
Warning: Failed to fetch file for ID 951

Fetching code + source files: 400it [01:34,  3.66it/s]

Saved batch of 17 entries.

Fetching code + source files: 406it [01:35,  4.07it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/tests/org.eclipse.wst.html.core.tests/src/org/eclipse/wst/html/core/tests/format/TestFormatProcessorHTML.java (status: 404)
Warning: Failed to fetch file for ID 960
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/tests/org.eclipse.wst.html.core.tests/src/org/eclipse/wst/html/core/tests/format/TestFormatProcessorHTML.java (status: 404)
Warning: Failed to fetch file for ID 961

Fetching code + source files: 409it [01:35,  5.00it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.ui/src-multipage/org/eclipse/wst/xml/ui/internal/tabletree/XMLTableTreeViewer.java (status: 404)
Warning: Failed to fetch file for ID 962
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.ui/src-multipage/org/eclipse/wst/xml/ui/internal/tabletree/XMLTableTreeViewer.java (status: 404)
Warning: Failed to fetch file for ID 963

Fetching code + source files: 411it [01:36,  5.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.core/src/org/eclipse/wst/html/core/internal/contentmodel/HedA.java (status: 404)
Warning: Failed to fetch file for ID 964
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.core/src/org/eclipse/wst/html/core/internal/contentmodel/HedA.java (status: 404)
Warning: Failed to fetch file for ID 965

Fetching code + source files: 413it [01:36,  4.98it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.jst.jsp.core/src/org/eclipse/jst/jsp/core/internal/java/jspel/SimpleNode.java (status: 404)
Warning: Failed to fetch file for ID 966
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.jst.jsp.core/src/org/eclipse/jst/jsp/core/internal/java/jspel/SimpleNode.java (status: 404)
Warning: Failed to fetch file for ID 967

Fetching code + source files: 414it [01:37,  4.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.launching/src/org/eclipse/dltk/launching/IInterpreterRunner.java (status: 404)
Warning: Failed to fetch file for ID 968
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.launching/src/org/eclipse/dltk/launching/IInterpreterRunner.java (status: 404)
Warning: Failed to fetch file for ID 969

Fetching code + source files: 416it [01:37,  4.40it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src-contentmodel/org/eclipse/wst/xml/core/internal/contentmodel/modelquery/IExternalSchemaLocationProvider.java (status: 404)
Warning: Failed to fetch file for ID 970
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src-contentmodel/org/eclipse/wst/xml/core/internal/contentmodel/modelquery/IExternalSchemaLocationProvider.java (status: 404)
Warning: Failed to fetch file for ID 971

Fetching code + source files: 419it [01:38,  5.15it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/design/editparts/XSDSchemaEditPart.java (status: 404)
Warning: Failed to fetch file for ID 972
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/design/editparts/XSDSchemaEditPart.java (status: 404)
Warning: Failed to fetch file for ID 973

Fetching code + source files: 425it [01:39,  4.68it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/IDLTKDebugUIPreferenceConstants.java (status: 404)
Warning: Failed to fetch file for ID 980
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/IDLTKDebugUIPreferenceConstants.java (status: 404)
Warning: Failed to fetch file for ID 981

Fetching code + source files: 426it [01:39,  3.91it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/CustomizePerspectiveDialog.java (status: 404)
Warning: Failed to fetch file for ID 982
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/CustomizePerspectiveDialog.java (status: 404)
Warning: Failed to fetch file for ID 983

Fetching code + source files: 434it [01:41,  4.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/mylyn/plugins/org.eclipse.dltk.mylyn/src/org/eclipse/dltk/internal/mylyn/search/Messages.java (status: 404)
Warning: Failed to fetch file for ID 994
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/mylyn/plugins/org.eclipse.dltk.mylyn/src/org/eclipse/dltk/internal/mylyn/search/Messages.java (status: 404)
Warning: Failed to fetch file for ID 995

Fetching code + source files: 450it [01:45,  3.86it/s]

Saved batch of 30 entries.

Fetching code + source files: 500it [01:57,  3.45it/s]

Saved batch of 50 entries.

Fetching code + source files: 550it [02:09,  3.43it/s]

Saved batch of 50 entries.

Fetching code + source files: 598it [02:19,  5.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 1218
Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 1219

Fetching code + source files: 601it [02:20,  4.60it/s]

Saved batch of 48 entries.

Fetching code + source files: 650it [02:32,  4.14it/s]

Saved batch of 50 entries.

Fetching code + source files: 700it [02:44,  4.00it/s]

Saved batch of 50 entries.

Fetching code + source files: 751it [02:57,  3.80it/s]

Saved batch of 50 entries.

Fetching code + source files: 800it [03:09,  3.11it/s]

Saved batch of 50 entries.

Fetching code + source files: 850it [03:21,  3.02it/s]

Saved batch of 50 entries.

Fetching code + source files: 900it [03:33,  3.39it/s]

Saved batch of 50 entries.

Fetching code + source files: 938it [03:41,  4.17it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/bpsim/FloatingParameterType.java (status: 404)
Warning: Failed to fetch file for ID 1671
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/bpsim/FloatingParameterType.java (status: 404)
Warning: Failed to fetch file for ID 1672

Fetching code + source files: 942it [03:42,  4.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 1675
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 1676

Fetching code + source files: 945it [03:43,  5.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/preferences/Bpmn2EditorAppearancePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 1677
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/preferences/Bpmn2EditorAppearancePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 1678

Fetching code + source files: 946it [03:43,  4.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/lane/RotateLaneFeature.java (status: 404)
Warning: Failed to fetch file for ID 1679
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/lane/RotateLaneFeature.java (status: 404)
Warning: Failed to fetch file for ID 1680

Fetching code + source files: 948it [03:43,  4.90it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/AssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 1681
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/AssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 1682
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/utils/GraphicsUtil.java (status: 404)
Warning: Failed to fetch file for ID 1683

Fetching code + source files: 951it [03:44,  4.08it/s]

Saved batch of 39 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/utils/GraphicsUtil.java (status: 404)
Warning: Failed to fetch file for ID 1684

Fetching code + source files: 953it [03:45,  3.27it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/activity/task/ServiceTaskFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 1685
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/activity/task/ServiceTaskFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 1686

Fetching code + source files: 955it [03:46,  3.88it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/bpsim/impl/BpsimPackageImpl.java (status: 404)
Warning: Failed to fetch file for ID 1687
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/bpsim/impl/BpsimPackageImpl.java (status: 404)
Warning: Failed to fetch file for ID 1688

Fetching code + source files: 956it [03:46,  3.39it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/editor/BPMN2EditorUpdateBehavior.java (status: 404)
Warning: Failed to fetch file for ID 1691
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/editor/BPMN2EditorUpdateBehavior.java (status: 404)
Warning: Failed to fetch file for ID 1692

Fetching code + source files: 958it [03:46,  4.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/features/event/EventSelectionBehavior.java (status: 404)
Warning: Failed to fetch file for ID 1693
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/features/event/EventSelectionBehavior.java (status: 404)
Warning: Failed to fetch file for ID 1694

Fetching code + source files: 960it [03:47,  4.20it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/editor/BPMN2MultiPageEditor.java (status: 404)
Warning: Failed to fetch file for ID 1695
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/editor/BPMN2MultiPageEditor.java (status: 404)
Warning: Failed to fetch file for ID 1696

Fetching code + source files: 962it [03:47,  4.42it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/drools/impl/DroolsFactoryImpl.java (status: 404)
Warning: Failed to fetch file for ID 1697
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/drools/impl/DroolsFactoryImpl.java (status: 404)
Warning: Failed to fetch file for ID 1698

Fetching code + source files: 964it [03:48,  4.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/dialogs/ViewerFileFilter.java (status: 404)
Warning: Failed to fetch file for ID 1701
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/dialogs/ViewerFileFilter.java (status: 404)
Warning: Failed to fetch file for ID 1702

Fetching code + source files: 967it [03:48,  5.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/clad/ListAndDetailCompositeBase.java (status: 404)
Warning: Failed to fetch file for ID 1703
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/clad/ListAndDetailCompositeBase.java (status: 404)
Warning: Failed to fetch file for ID 1704

Fetching code + source files: 969it [03:49,  5.29it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/editors/ttcn3editor/DocumentSetupParticipant.java (status: 404)
Warning: Failed to fetch file for ID 1709
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/editors/ttcn3editor/DocumentSetupParticipant.java (status: 404)
Warning: Failed to fetch file for ID 1710

Fetching code + source files: 971it [03:49,  4.33it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 1711
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 1712

Fetching code + source files: 974it [03:50,  4.38it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium/src/org/eclipse/titanium/graph/gui/layouts/TitaniumDAGLayout.java (status: 404)
Warning: Failed to fetch file for ID 1715
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium/src/org/eclipse/titanium/graph/gui/layouts/TitaniumDAGLayout.java (status: 404)
Warning: Failed to fetch file for ID 1716

Fetching code + source files: 977it [03:51,  4.70it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/subtypes/StringSetConstraint.java (status: 404)
Warning: Failed to fetch file for ID 1717
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/subtypes/StringSetConstraint.java (status: 404)
Warning: Failed to fetch file for ID 1718

Fetching code + source files: 992it [03:54,  4.50it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 1733
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 1734

Fetching code + source files: 1000it [03:56,  3.02it/s]

Saved batch of 23 entries.

Fetching code + source files: 1006it [03:58,  3.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.regressiontests/src/org/eclipse/titan/regressiontests/designer/statictests/Basic_tests/AST_Syntax_warning_tests.java (status: 404)
Warning: Failed to fetch file for ID 1749
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.regressiontests/src/org/eclipse/titan/regressiontests/designer/statictests/Basic_tests/AST_Syntax_warning_tests.java (status: 404)
Warning: Failed to fetch file for ID 1750

Fetching code + source files: 1016it [04:01,  3.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 1759
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 1760

Fetching code + source files: 1026it [04:03,  4.30it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/message/MessageElement.java (status: 404)
Warning: Failed to fetch file for ID 1771
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/message/MessageElement.java (status: 404)
Warning: Failed to fetch file for ID 1772

Fetching code + source files: 1030it [04:04,  4.53it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 1775
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 1776

Fetching code + source files: 1036it [04:06,  3.93it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/ParameterisedSubReference.java (status: 404)
Warning: Failed to fetch file for ID 1781
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/ParameterisedSubReference.java (status: 404)
Warning: Failed to fetch file for ID 1782

Fetching code + source files: 1051it [04:12,  3.04it/s]

Saved batch of 40 entries.

Fetching code + source files: 1100it [04:24,  3.28it/s]

Saved batch of 50 entries.

Fetching code + source files: 1151it [04:37,  3.02it/s]

Saved batch of 50 entries.

Fetching code + source files: 1200it [04:49,  2.34it/s]

Saved batch of 50 entries.

Fetching code + source files: 1251it [05:01,  2.95it/s]

Saved batch of 50 entries.

Fetching code + source files: 1301it [05:14,  2.55it/s]

Saved batch of 50 entries.

Fetching code + source files: 1351it [05:29,  1.79it/s]

Saved batch of 50 entries.

Fetching code + source files: 1401it [05:47,  1.05s/it]

Saved batch of 50 entries.

Fetching code + source files: 1451it [06:07,  1.41s/it]

Saved batch of 50 entries.

Fetching code + source files: 1463it [06:10,  3.74it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet144.java (status: 404)
Warning: Failed to fetch file for ID 2277
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet144.java (status: 404)
Warning: Failed to fetch file for ID 2278

Fetching code + source files: 1465it [06:11,  3.96it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/TextLayout.java (status: 404)
Warning: Failed to fetch file for ID 2281
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/TextLayout.java (status: 404)
Warning: Failed to fetch file for ID 2282

Fetching code + source files: 1467it [06:11,  4.02it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Accessibility/win32/org/eclipse/swt/accessibility/Accessible.java (status: 404)
Warning: Failed to fetch file for ID 2283
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Accessibility/win32/org/eclipse/swt/accessibility/Accessible.java (status: 404)
Warning: Failed to fetch file for ID 2284

Fetching code + source files: 1501it [06:27,  1.48s/it]

Saved batch of 44 entries.

Fetching code + source files: 1515it [06:31,  3.82it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/builder/unknowncontent/InputStreamDataSource.java (status: 404)
Warning: Failed to fetch file for ID 2347
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/builder/unknowncontent/InputStreamDataSource.java (status: 404)
Warning: Failed to fetch file for ID 2348

Fetching code + source files: 1517it [06:31,  3.91it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/receivers/AbstractMessageReceiver.java (status: 404)
Warning: Failed to fetch file for ID 2349
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/receivers/AbstractMessageReceiver.java (status: 404)
Warning: Failed to fetch file for ID 2350

Fetching code + source files: 1518it [06:32,  3.38it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/samples/userguide/src/userguide/clients/EchoNonBlockingClient.java (status: 404)
Warning: Failed to fetch file for ID 2351

Fetching code + source files: 1519it [06:32,  3.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/samples/userguide/src/userguide/clients/EchoNonBlockingClient.java (status: 404)
Warning: Failed to fetch file for ID 2352

Fetching code + source files: 1523it [06:33,  3.82it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/description/ModuleConfiguration.java (status: 404)
Warning: Failed to fetch file for ID 2355
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/description/ModuleConfiguration.java (status: 404)
Warning: Failed to fetch file for ID 2356

Fetching code + source files: 1525it [06:34,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/util/CommandLineOption.java (status: 404)
Warning: Failed to fetch file for ID 2357
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/util/CommandLineOption.java (status: 404)
Warning: Failed to fetch file for ID 2358

Fetching code + source files: 1527it [06:34,  4.46it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/testkit/src/main/java/org/apache/axis2/transport/testkit/endpoint/AsyncEndpoint.java (status: 404)
Warning: Failed to fetch file for ID 2359
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/testkit/src/main/java/org/apache/axis2/transport/testkit/endpoint/AsyncEndpoint.java (status: 404)
Warning: Failed to fetch file for ID 2360

Fetching code + source files: 1551it [06:46,  1.39s/it]

Saved batch of 38 entries.

Fetching code + source files: 1601it [07:06,  1.48s/it]

Saved batch of 50 entries.

Fetching code + source files: 1651it [07:26,  1.43s/it]

Saved batch of 50 entries.

Fetching code + source files: 1700it [07:47,  2.02s/it]

Saved batch of 50 entries.

Fetching code + source files: 1750it [08:07,  2.13s/it]

Saved batch of 50 entries.

Fetching code + source files: 1757it [08:09,  2.35it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-ytex/src/main/java/org/apache/ctakes/ytex/kernel/metric/LinMetric.java (status: 404)
Warning: Failed to fetch file for ID 2619
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-ytex/src/main/java/org/apache/ctakes/ytex/kernel/metric/LinMetric.java (status: 404)
Warning: Failed to fetch file for ID 2620

Fetching code + source files: 1761it [08:11,  3.40it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 2623
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 2624

Fetching code + source files: 1763it [08:11,  3.41it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/cc/jdbc/i2b2/ObservationFactRow.java (status: 404)
Warning: Failed to fetch file for ID 2625
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/cc/jdbc/i2b2/ObservationFactRow.java (status: 404)
Warning: Failed to fetch file for ID 2626

Fetching code + source files: 1769it [08:13,  3.71it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/cc/html/JsWriter.java (status: 404)
Warning: Failed to fetch file for ID 2631
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/cc/html/JsWriter.java (status: 404)
Warning: Failed to fetch file for ID 2632

Fetching code + source files: 1801it [08:28,  1.44s/it]

Saved batch of 42 entries.

Fetching code + source files: 1851it [08:49,  1.61s/it]

Saved batch of 50 entries.

Fetching code + source files: 1861it [08:51,  3.61it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.ui.tests/src/org/eclipse/linuxtools/internal/docker/ui/testutils/MockImageInfoFactory.java (status: 404)
Warning: Failed to fetch file for ID 2731
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.ui.tests/src/org/eclipse/linuxtools/internal/docker/ui/testutils/MockImageInfoFactory.java (status: 404)
Warning: Failed to fetch file for ID 2732

Fetching code + source files: 1863it [08:52,  3.69it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/copy/serializing/CopyDataToClipboardSerializer.java (status: 404)
Warning: Failed to fetch file for ID 2733
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/copy/serializing/CopyDataToClipboardSerializer.java (status: 404)
Warning: Failed to fetch file for ID 2734

Fetching code + source files: 1877it [08:56,  4.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ReferenceCounter.java (status: 404)
Warning: Failed to fetch file for ID 2747
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ReferenceCounter.java (status: 404)
Warning: Failed to fetch file for ID 2748

Fetching code + source files: 1901it [09:08,  1.41s/it]

Saved batch of 44 entries.

Fetching code + source files: 1917it [09:13,  3.73it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/ScriptElementProperties.java (status: 404)
Warning: Failed to fetch file for ID 2793
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/ScriptElementProperties.java (status: 404)
Warning: Failed to fetch file for ID 2794

Fetching code + source files: 1949it [09:22,  3.66it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/dialogs/TypeFilteringDialog.java (status: 404)
Warning: Failed to fetch file for ID 2835

Fetching code + source files: 1951it [09:28,  1.39s/it]

Saved batch of 47 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/dialogs/TypeFilteringDialog.java (status: 404)
Warning: Failed to fetch file for ID 2836

Fetching code + source files: 1989it [09:39,  3.79it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/dialogs/ComboObjectEditor.java (status: 404)
Warning: Failed to fetch file for ID 2873
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/dialogs/ComboObjectEditor.java (status: 404)
Warning: Failed to fetch file for ID 2874

Fetching code + source files: 2001it [09:48,  1.53s/it]

Saved batch of 47 entries.

Fetching code + source files: 2016it [09:53,  3.88it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/bindings/keys/KeySequenceText.java (status: 404)
Warning: Failed to fetch file for ID 2904
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/bindings/keys/KeySequenceText.java (status: 404)
Warning: Failed to fetch file for ID 2905

Fetching code + source files: 2020it [09:54,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 2908
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 2909

Fetching code + source files: 2022it [09:54,  4.19it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java (status: 404)
Warning: Failed to fetch file for ID 2910
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java (status: 404)
Warning: Failed to fetch file for ID 2911

Fetching code + source files: 2050it [10:09,  2.14s/it]

Saved batch of 44 entries.

Fetching code + source files: 2052it [10:09,  1.20s/it]

Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/self-service/src/main/java/com/epam/dlab/backendapi/resources/callback/azure/KeyUploaderCallbackAzure.java (status: 404)
Warning: Failed to fetch file for ID 2946
Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/self-service/src/main/java/com/epam/dlab/backendapi/resources/callback/azure/KeyUploaderCallbackAzure.java (status: 404)
Warning: Failed to fetch file for ID 2947

Fetching code + source files: 2075it [10:16,  3.70it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.examples/src/org/eclipse/nebula/widgets/nattable/examples/_300_Data/_304_DynamicColumnExample.java (status: 404)
Warning: Failed to fetch file for ID 2972
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.examples/src/org/eclipse/nebula/widgets/nattable/examples/_300_Data/_304_DynamicColumnExample.java (status: 404)
Warning: Failed to fetch file for ID 2973

Fetching code + source files: 2084it [10:18,  3.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/readers/SequentialLogFileReader.java (status: 404)
Warning: Failed to fetch file for ID 2982
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/readers/SequentialLogFileReader.java (status: 404)
Warning: Failed to fetch file for ID 2983

Fetching code + source files: 2096it [10:21,  4.62it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/internal/core/search/matching/MethodLocator.java (status: 404)
Warning: Failed to fetch file for ID 2996
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/internal/core/search/matching/MethodLocator.java (status: 404)
Warning: Failed to fetch file for ID 2997

Fetching code + source files: 2098it [10:22,  4.88it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/client/Call.java (status: 404)
Warning: Failed to fetch file for ID 2998
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/client/Call.java (status: 404)
Warning: Failed to fetch file for ID 2999

Fetching code + source files: 2100it [10:28,  1.77s/it]

Saved batch of 40 entries.

Fetching code + source files: 2110it [10:31,  3.19it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.http.server/src/org/eclipse/jgit/http/server/resolver/DefaultReceivePackFactory.java (status: 404)
Warning: Failed to fetch file for ID 3012
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.http.server/src/org/eclipse/jgit/http/server/resolver/DefaultReceivePackFactory.java (status: 404)
Warning: Failed to fetch file for ID 3013

Fetching code + source files: 2125it [10:35,  4.03it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/model/org/eclipse/dltk/core/PreferencesLookupDelegate.java (status: 404)
Warning: Failed to fetch file for ID 3029
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/model/org/eclipse/dltk/core/PreferencesLookupDelegate.java (status: 404)
Warning: Failed to fetch file for ID 3030

Fetching code + source files: 2150it [10:50,  2.41s/it]

Saved batch of 46 entries.

Fetching code + source files: 2152it [10:50,  1.30s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IViewReference.java (status: 404)
Warning: Failed to fetch file for ID 3064
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IViewReference.java (status: 404)
Warning: Failed to fetch file for ID 3065

Fetching code + source files: 2176it [10:57,  3.94it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/VariableBlock.java (status: 404)
Warning: Failed to fetch file for ID 3088
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/VariableBlock.java (status: 404)
Warning: Failed to fetch file for ID 3089

Fetching code + source files: 2184it [11:00,  3.95it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/json/bundles/org.eclipse.wst.json.core/src/org/eclipse/wst/json/core/internal/document/JSONNodeImpl.java (status: 404)
Warning: Failed to fetch file for ID 3096
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/json/bundles/org.eclipse.wst.json.core/src/org/eclipse/wst/json/core/internal/document/JSONNodeImpl.java (status: 404)
Warning: Failed to fetch file for ID 3097

Fetching code + source files: 2200it [11:12,  2.38s/it]

Saved batch of 44 entries.

Fetching code + source files: 2208it [11:14,  2.76it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/corba/src/org/apache/axis2/corba/deployer/SchemaGenerator.java (status: 404)
Warning: Failed to fetch file for ID 3134
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/corba/src/org/apache/axis2/corba/deployer/SchemaGenerator.java (status: 404)
Warning: Failed to fetch file for ID 3135

Fetching code + source files: 2250it [11:31,  2.06s/it]

Saved batch of 48 entries.

Fetching code + source files: 2258it [11:34,  2.96it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/text/spelling/ScriptSpellingReconcileStrategy.java (status: 404)
Warning: Failed to fetch file for ID 3192
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/text/spelling/ScriptSpellingReconcileStrategy.java (status: 404)
Warning: Failed to fetch file for ID 3193

Fetching code + source files: 2262it [11:35,  3.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT OpenGL/common/org/eclipse/swt/opengl/GLData.java (status: 404)
Warning: Failed to fetch file for ID 3196
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT OpenGL/common/org/eclipse/swt/opengl/GLData.java (status: 404)
Warning: Failed to fetch file for ID 3197

Fetching code + source files: 2280it [11:40,  3.99it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-assertion-zoner/src/main/java/org/mitre/medfacts/uima/RunZoner.java (status: 404)
Warning: Failed to fetch file for ID 3216
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-assertion-zoner/src/main/java/org/mitre/medfacts/uima/RunZoner.java (status: 404)
Warning: Failed to fetch file for ID 3217

Fetching code + source files: 2300it [11:51,  2.02s/it]

Saved batch of 44 entries.

Fetching code + source files: 2350it [12:10,  1.68s/it]

Saved batch of 50 entries.

Fetching code + source files: 2380it [12:18,  4.34it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/ColumnLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 3332
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/ColumnLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 3333

Fetching code + source files: 2400it [12:29,  2.08s/it]

Saved batch of 48 entries.

Fetching code + source files: 2408it [12:31,  2.84it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/commentelement/impl/BasicCommentElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 3368
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/commentelement/impl/BasicCommentElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 3369

Fetching code + source files: 2430it [12:37,  3.89it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/drools/DroolsFactory.java (status: 404)
Warning: Failed to fetch file for ID 3392
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/model/drools/DroolsFactory.java (status: 404)
Warning: Failed to fetch file for ID 3393

Fetching code + source files: 2450it [12:49,  2.06s/it]

Saved batch of 46 entries.

Fetching code + source files: 2454it [12:50,  1.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/WWinPartService.java (status: 404)
Warning: Failed to fetch file for ID 3418
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/WWinPartService.java (status: 404)
Warning: Failed to fetch file for ID 3419

Fetching code + source files: 2501it [13:06,  1.01it/s]

Saved batch of 48 entries.

Fetching code + source files: 2548it [13:18,  4.37it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/internal/core/search/TypeNameMatchRequestorWrapper.java (status: 404)
Warning: Failed to fetch file for ID 3521
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/internal/core/search/TypeNameMatchRequestorWrapper.java (status: 404)
Warning: Failed to fetch file for ID 3522

Fetching code + source files: 2551it [13:22,  1.20it/s]

Saved batch of 48 entries.

Fetching code + source files: 2563it [13:26,  4.37it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/AbstractEvaluationHandler.java (status: 404)
Warning: Failed to fetch file for ID 3539
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/AbstractEvaluationHandler.java (status: 404)
Warning: Failed to fetch file for ID 3540

Fetching code + source files: 2601it [13:39,  1.04it/s]

Saved batch of 48 entries.

Fetching code + source files: 2641it [13:49,  5.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/ViewerTestDTD.java (status: 404)
Warning: Failed to fetch file for ID 3637
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/ViewerTestDTD.java (status: 404)
Warning: Failed to fetch file for ID 3638

Fetching code + source files: 2649it [13:51,  4.89it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/api/RevertCommand.java (status: 404)
Warning: Failed to fetch file for ID 3647

Fetching code + source files: 2651it [13:55,  1.02s/it]

Saved batch of 47 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/api/RevertCommand.java (status: 404)
Warning: Failed to fetch file for ID 3648

Fetching code + source files: 2657it [13:57,  3.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/PageEventAction.java (status: 404)
Warning: Failed to fetch file for ID 3657
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/PageEventAction.java (status: 404)
Warning: Failed to fetch file for ID 3658

Fetching code + source files: 2701it [14:12,  1.19it/s]

Saved batch of 47 entries.

Fetching code + source files: 2726it [14:19,  3.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ViewerActionBuilder.java (status: 404)
Warning: Failed to fetch file for ID 3735
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ViewerActionBuilder.java (status: 404)
Warning: Failed to fetch file for ID 3736

Fetching code + source files: 2751it [14:29,  1.18it/s]

Saved batch of 48 entries.

Fetching code + source files: 2753it [14:30,  1.76it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/ValueRange.java (status: 404)
Warning: Failed to fetch file for ID 3763
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/ValueRange.java (status: 404)
Warning: Failed to fetch file for ID 3764

Fetching code + source files: 2800it [14:48,  2.07s/it]

Saved batch of 48 entries.

Fetching code + source files: 2811it [14:51,  3.39it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/FileTransport.java (status: 404)
Warning: Failed to fetch file for ID 3838
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/FileTransport.java (status: 404)
Warning: Failed to fetch file for ID 3839

Fetching code + source files: 2848it [15:01,  4.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/dialogs/DeprecatedUIWizardsAuto.java (status: 404)
Warning: Failed to fetch file for ID 3878
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/dialogs/DeprecatedUIWizardsAuto.java (status: 404)
Warning: Failed to fetch file for ID 3879

Fetching code + source files: 2850it [15:09,  2.57s/it]

Saved batch of 46 entries.

Fetching code + source files: 2890it [15:21,  3.94it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/fillhandle/FillHandleLayerPainter.java (status: 404)
Warning: Failed to fetch file for ID 3924
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/fillhandle/FillHandleLayerPainter.java (status: 404)
Warning: Failed to fetch file for ID 3925

Fetching code + source files: 2900it [15:31,  2.53s/it]

Saved batch of 48 entries.

Fetching code + source files: 2906it [15:33,  1.95it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/artifact/CreateTextAnnotationFeature.java (status: 404)
Warning: Failed to fetch file for ID 3942
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/artifact/CreateTextAnnotationFeature.java (status: 404)
Warning: Failed to fetch file for ID 3943

Fetching code + source files: 2928it [15:39,  4.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 3970
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 3971

Fetching code + source files: 2932it [15:40,  4.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/ASN1/types/ExtensionAdditions.java (status: 404)
Warning: Failed to fetch file for ID 3974
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/ASN1/types/ExtensionAdditions.java (status: 404)
Warning: Failed to fetch file for ID 3975

Fetching code + source files: 2940it [15:42,  4.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core.index.sql/src/org/eclipse/dltk/core/index/sql/IElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 3986
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core.index.sql/src/org/eclipse/dltk/core/index/sql/IElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 3987

Fetching code + source files: 2944it [15:43,  4.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xpath/bundles/org.eclipse.wst.xml.xpath2.processor/src/org/eclipse/wst/xml/xpath2/processor/internal/function/FnStringToCodepoints.java (status: 404)
Warning: Failed to fetch file for ID 3990
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xpath/bundles/org.eclipse.wst.xml.xpath2.processor/src/org/eclipse/wst/xml/xpath2/processor/internal/function/FnStringToCodepoints.java (status: 404)
Warning: Failed to fetch file for ID 3991

Fetching code + source files: 2950it [15:53,  2.63s/it]

Saved batch of 40 entries.

Fetching code + source files: 2966it [15:58,  3.33it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/tests/org.eclipse.wst.html.ui.tests/src/org/eclipse/wst/html/ui/tests/HTMLUITestsPlugin.java (status: 404)
Warning: Failed to fetch file for ID 4013
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/tests/org.eclipse.wst.html.ui.tests/src/org/eclipse/wst/html/ui/tests/HTMLUITestsPlugin.java (status: 404)
Warning: Failed to fetch file for ID 4015

Fetching code + source files: 3000it [16:17,  2.65s/it]

Saved batch of 48 entries.

Fetching code + source files: 3032it [16:26,  4.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/metadata/src/org/apache/axis2/jaxws/description/DescriptionKey.java (status: 404)
Warning: Failed to fetch file for ID 4092
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/metadata/src/org/apache/axis2/jaxws/description/DescriptionKey.java (status: 404)
Warning: Failed to fetch file for ID 4093

Fetching code + source files: 3050it [16:40,  2.60s/it]

Saved batch of 48 entries.

Fetching code + source files: 3084it [16:50,  3.94it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/css2/CSSPropertyFontSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 4162
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/css2/CSSPropertyFontSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 4163

Fetching code + source files: 3100it [17:02,  2.72s/it]

Saved batch of 48 entries.

Fetching code + source files: 3108it [17:04,  2.70it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/custom/ScrolledComposite.java (status: 404)
Warning: Failed to fetch file for ID 4186
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/custom/ScrolledComposite.java (status: 404)
Warning: Failed to fetch file for ID 4187

Fetching code + source files: 3150it [17:24,  2.93s/it]

Saved batch of 48 entries.

Fetching code + source files: 3187it [17:35,  4.31it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 4285
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 4286

Fetching code + source files: 3200it [17:44,  1.35s/it]

Saved batch of 48 entries.

Fetching code + source files: 3208it [17:46,  2.41it/s]

Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/provisioning-service/src/main/java/com/epam/dlab/backendapi/resources/aws/ComputationalResourceAws.java (status: 404)
Warning: Failed to fetch file for ID 4307

Fetching code + source files: 3219it [17:48,  4.07it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/preferences/pages/RegexpEntryDialog.java (status: 404)
Warning: Failed to fetch file for ID 4328
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/preferences/pages/RegexpEntryDialog.java (status: 404)
Warning: Failed to fetch file for ID 4329

Fetching code + source files: 3223it [17:49,  4.69it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xpath/bundles/org.eclipse.wst.xml.xpath2.processor/src/org/eclipse/wst/xml/xpath2/processor/internal/function/FnLowerCase.java (status: 404)
Warning: Failed to fetch file for ID 4338
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xpath/bundles/org.eclipse.wst.xml.xpath2.processor/src/org/eclipse/wst/xml/xpath2/processor/internal/function/FnLowerCase.java (status: 404)
Warning: Failed to fetch file for ID 4339

Fetching code + source files: 3229it [17:50,  4.79it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/ToolBar.java (status: 404)
Warning: Failed to fetch file for ID 4344
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/ToolBar.java (status: 404)
Warning: Failed to fetch file for ID 4345

Fetching code + source files: 3250it [18:00,  1.05s/it]

Saved batch of 43 entries.

Fetching code + source files: 3251it [18:00,  1.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 4375
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 4376

Fetching code + source files: 3289it [18:09,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/menu/impl/HandledMenuItemImpl.java (status: 404)
Warning: Failed to fetch file for ID 4417
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/menu/impl/HandledMenuItemImpl.java (status: 404)
Warning: Failed to fetch file for ID 4418

Fetching code + source files: 3295it [18:11,  4.34it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/themes/WorkbenchThemeManager.java (status: 404)
Warning: Failed to fetch file for ID 4423
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/themes/WorkbenchThemeManager.java (status: 404)
Warning: Failed to fetch file for ID 4424

Fetching code + source files: 3300it [18:17,  1.08s/it]

Saved batch of 44 entries.

Fetching code + source files: 3350it [18:33,  1.15s/it]

Saved batch of 50 entries.

Fetching code + source files: 3400it [18:51,  1.19s/it]

Saved batch of 50 entries.

Fetching code + source files: 3429it [18:59,  4.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium/src/org/eclipse/titanium/graph/clustering/PathCluster.java (status: 404)
Warning: Failed to fetch file for ID 4579
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium/src/org/eclipse/titanium/graph/clustering/PathCluster.java (status: 404)
Warning: Failed to fetch file for ID 4580

Fetching code + source files: 3432it [18:59,  4.35it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/lib/Ref.java (status: 404)
Warning: Failed to fetch file for ID 4583
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/lib/Ref.java (status: 404)
Warning: Failed to fetch file for ID 4584

Fetching code + source files: 3438it [19:01,  4.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.extension.poi/src/org/eclipse/nebula/widgets/nattable/extension/poi/ExcelCellStyleAttributes.java (status: 404)
Warning: Failed to fetch file for ID 4589
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.extension.poi/src/org/eclipse/nebula/widgets/nattable/extension/poi/ExcelCellStyleAttributes.java (status: 404)
Warning: Failed to fetch file for ID 4590

Fetching code + source files: 3451it [19:09,  1.14it/s]

Saved batch of 44 entries.

Fetching code + source files: 3501it [19:27,  1.00s/it]

Saved batch of 50 entries.

Fetching code + source files: 3521it [19:32,  4.58it/s]

Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-webapp-common/src/main/java/com/epam/dlab/rest/mappers/ResourceNotFoundExceptionMapper.java (status: 404)
Warning: Failed to fetch file for ID 4675
Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-webapp-common/src/main/java/com/epam/dlab/rest/mappers/ResourceNotFoundExceptionMapper.java (status: 404)
Warning: Failed to fetch file for ID 4676

Fetching code + source files: 3524it [19:32,  4.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/LZWCodec.java (status: 404)
Warning: Failed to fetch file for ID 4679
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/LZWCodec.java (status: 404)
Warning: Failed to fetch file for ID 4680

Fetching code + source files: 3534it [19:35,  4.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ScopeAndMetricOnlySchemaRecordList.java (status: 404)
Warning: Failed to fetch file for ID 4689
Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ScopeAndMetricOnlySchemaRecordList.java (status: 404)
Warning: Failed to fetch file for ID 4690

Fetching code + source files: 3550it [19:44,  1.28s/it]

Saved batch of 44 entries.

Fetching code + source files: 3554it [19:45,  1.54it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/text/hover/AnnotationExpandHover.java (status: 404)
Warning: Failed to fetch file for ID 4715
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/text/hover/AnnotationExpandHover.java (status: 404)
Warning: Failed to fetch file for ID 4716

Fetching code + source files: 3574it [19:49,  3.99it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.core/DevTimeSupport/HeadParsers/XML10Names/XML10Names.java (status: 404)
Warning: Failed to fetch file for ID 4741
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.core/DevTimeSupport/HeadParsers/XML10Names/XML10Names.java (status: 404)
Warning: Failed to fetch file for ID 4742

Fetching code + source files: 3580it [19:51,  4.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/internal/webkit/WebKitGTK.java (status: 404)
Warning: Failed to fetch file for ID 4749
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/internal/webkit/WebKitGTK.java (status: 404)
Warning: Failed to fetch file for ID 4750

Fetching code + source files: 3600it [20:01,  1.20s/it]

Saved batch of 44 entries.

Fetching code + source files: 3605it [20:02,  1.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.ui.editor/src/org/eclipse/linuxtools/internal/valgrind/ui/editor/wizards/NewSuppressionWizard.java (status: 404)
Warning: Failed to fetch file for ID 4777
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.ui.editor/src/org/eclipse/linuxtools/internal/valgrind/ui/editor/wizards/NewSuppressionWizard.java (status: 404)
Warning: Failed to fetch file for ID 4778

Fetching code + source files: 3626it [20:07,  4.31it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.views/src/org/eclipse/ui/views/properties/IPropertyDescriptor.java (status: 404)
Warning: Failed to fetch file for ID 4803
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.views/src/org/eclipse/ui/views/properties/IPropertyDescriptor.java (status: 404)
Warning: Failed to fetch file for ID 4804

Fetching code + source files: 3632it [20:09,  4.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.jface/src/org/eclipse/jface/viewers/SWTFocusCellManager.java (status: 404)
Warning: Failed to fetch file for ID 4813
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.jface/src/org/eclipse/jface/viewers/SWTFocusCellManager.java (status: 404)
Warning: Failed to fetch file for ID 4814

Fetching code + source files: 3651it [20:19,  1.02it/s]

Saved batch of 44 entries.

Fetching code + source files: 3689it [20:29,  4.36it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java (status: 404)
Warning: Failed to fetch file for ID 4879
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java (status: 404)
Warning: Failed to fetch file for ID 4880

Fetching code + source files: 3701it [20:38,  1.02s/it]

Saved batch of 48 entries.

Fetching code + source files: 3710it [20:40,  3.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/nsedit/SchemaPrefixChangeHandler.java (status: 404)
Warning: Failed to fetch file for ID 4901
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/nsedit/SchemaPrefixChangeHandler.java (status: 404)
Warning: Failed to fetch file for ID 4902

Fetching code + source files: 3748it [20:49,  4.27it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java (status: 404)
Warning: Failed to fetch file for ID 4941
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java (status: 404)
Warning: Failed to fetch file for ID 4942

Fetching code + source files: 3750it [20:56,  1.17s/it]

Saved batch of 46 entries.

Fetching code + source files: 3758it [20:58,  2.75it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextRenderer.java (status: 404)
Warning: Failed to fetch file for ID 4953
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextRenderer.java (status: 404)
Warning: Failed to fetch file for ID 4954

Fetching code + source files: 3798it [21:08,  3.93it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/description/ModuleConfiguration.java (status: 404)
Warning: Failed to fetch file for ID 5003

Fetching code + source files: 3801it [21:15,  1.06s/it]

Saved batch of 47 entries.
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/description/ModuleConfiguration.java (status: 404)
Warning: Failed to fetch file for ID 5004

Fetching code + source files: 3838it [21:24,  4.20it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug531667_Group_drawing_with_paint_listener_is_wrong.java (status: 404)
Warning: Failed to fetch file for ID 5049
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug531667_Group_drawing_with_paint_listener_is_wrong.java (status: 404)
Warning: Failed to fetch file for ID 5050

Fetching code + source files: 3851it [21:33,  1.39s/it]

Saved batch of 47 entries.

Fetching code + source files: 3856it [21:35,  1.96it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/testkit/src/main/java/org/apache/axis2/transport/testkit/http/JettyEchoEndpoint.java (status: 404)
Warning: Failed to fetch file for ID 5071
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/testkit/src/main/java/org/apache/axis2/transport/testkit/http/JettyEchoEndpoint.java (status: 404)
Warning: Failed to fetch file for ID 5072

Fetching code + source files: 3901it [21:53,  1.09s/it]

Saved batch of 48 entries.

Fetching code + source files: 3906it [21:54,  2.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests.databinding/src/org/eclipse/core/tests/databinding/observable/Diffs_ListDiffTests.java (status: 404)
Warning: Failed to fetch file for ID 5133
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests.databinding/src/org/eclipse/core/tests/databinding/observable/Diffs_ListDiffTests.java (status: 404)
Warning: Failed to fetch file for ID 5134

Fetching code + source files: 3923it [21:58,  4.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/BooleanCellEditor.java (status: 404)
Warning: Failed to fetch file for ID 5151
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/BooleanCellEditor.java (status: 404)
Warning: Failed to fetch file for ID 5152

Fetching code + source files: 3925it [21:58,  5.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/map/DelegatingMapProperty.java (status: 404)
Warning: Failed to fetch file for ID 5153
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/map/DelegatingMapProperty.java (status: 404)
Warning: Failed to fetch file for ID 5154

Fetching code + source files: 3949it [22:05,  4.40it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.editor/src/org/eclipse/linuxtools/internal/docker/editor/DockerConfiguration.java (status: 404)
Warning: Failed to fetch file for ID 5184
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.editor/src/org/eclipse/linuxtools/internal/docker/editor/DockerConfiguration.java (status: 404)
Warning: Failed to fetch file for ID 5185

Fetching code + source files: 3951it [22:12,  1.38s/it]

Saved batch of 42 entries.

Fetching code + source files: 3968it [22:16,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/EditorReference.java (status: 404)
Warning: Failed to fetch file for ID 5212
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/EditorReference.java (status: 404)
Warning: Failed to fetch file for ID 5213

Fetching code + source files: 4001it [22:31,  1.20s/it]

Saved batch of 48 entries.

Fetching code + source files: 4042it [22:40,  3.64it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/jaxws/src/org/apache/axis2/jaxws/binding/BindingUtils.java (status: 404)
Warning: Failed to fetch file for ID 5294
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/jaxws/src/org/apache/axis2/jaxws/binding/BindingUtils.java (status: 404)
Warning: Failed to fetch file for ID 5295

Fetching code + source files: 4044it [22:41,  4.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/PackWriter.java (status: 404)
Warning: Failed to fetch file for ID 5298
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/PackWriter.java (status: 404)
Warning: Failed to fetch file for ID 5299

Fetching code + source files: 4048it [22:42,  4.51it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/util/AttributeCalculator.java (status: 404)
Warning: Failed to fetch file for ID 5302
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/util/AttributeCalculator.java (status: 404)
Warning: Failed to fetch file for ID 5303

Fetching code + source files: 4051it [22:49,  1.13s/it]

Saved batch of 44 entries.

Fetching code + source files: 4054it [22:50,  1.50it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/text/hover/AnnotationExpansionControl.java (status: 404)
Warning: Failed to fetch file for ID 5308

Fetching code + source files: 4055it [22:50,  1.67it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/text/hover/AnnotationExpansionControl.java (status: 404)
Warning: Failed to fetch file for ID 5309

Fetching code + source files: 4074it [22:55,  4.51it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet113.java (status: 404)
Warning: Failed to fetch file for ID 5334
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet113.java (status: 404)
Warning: Failed to fetch file for ID 5335

Fetching code + source files: 4099it [23:00,  5.63it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/testkit/src/main/java/org/apache/axis2/transport/testkit/ManagedTestSuite.java (status: 404)
Warning: Failed to fetch file for ID 5368

Fetching code + source files: 4101it [23:08,  1.54s/it]

Saved batch of 45 entries.
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/testkit/src/main/java/org/apache/axis2/transport/testkit/ManagedTestSuite.java (status: 404)
Warning: Failed to fetch file for ID 5369

Fetching code + source files: 4150it [23:27,  1.35s/it]

Saved batch of 49 entries.

Fetching code + source files: 4198it [23:39,  4.54it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.examples/src/org/eclipse/nebula/widgets/nattable/examples/examples/_102_Configuration/AutomaticRowHeightExample.java (status: 404)
Warning: Failed to fetch file for ID 5482
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.examples/src/org/eclipse/nebula/widgets/nattable/examples/examples/_102_Configuration/AutomaticRowHeightExample.java (status: 404)
Warning: Failed to fetch file for ID 5483

Fetching code + source files: 4200it [23:47,  1.48s/it]

Saved batch of 48 entries.

Fetching code + source files: 4244it [23:57,  4.37it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/util/FSUtil.java (status: 404)
Warning: Failed to fetch file for ID 5530
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/util/FSUtil.java (status: 404)
Warning: Failed to fetch file for ID 5531

Fetching code + source files: 4250it [24:06,  1.35s/it]

Saved batch of 48 entries.

Fetching code + source files: 4284it [24:14,  4.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.model.edit/src/main/java/org/eclipse/m2e/model/edit/pom/impl/ReportSetImpl.java (status: 404)
Warning: Failed to fetch file for ID 5570
Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.model.edit/src/main/java/org/eclipse/m2e/model/edit/pom/impl/ReportSetImpl.java (status: 404)
Warning: Failed to fetch file for ID 5571

Fetching code + source files: 4294it [24:17,  3.85it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/nn/data/GoldEventPrinterWithLabels.java (status: 404)
Warning: Failed to fetch file for ID 5580
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/nn/data/GoldEventPrinterWithLabels.java (status: 404)
Warning: Failed to fetch file for ID 5581

Fetching code + source files: 4300it [24:26,  1.55s/it]

Saved batch of 46 entries.

Fetching code + source files: 4336it [24:35,  4.27it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core.manipulation/src/org/eclipse/dltk/internal/corext/refactoring/participants/ResourceModifications.java (status: 404)
Warning: Failed to fetch file for ID 5628
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core.manipulation/src/org/eclipse/dltk/internal/corext/refactoring/participants/ResourceModifications.java (status: 404)
Warning: Failed to fetch file for ID 5629

Fetching code + source files: 4339it [24:35,  4.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.ui.examples.readmetool/Eclipse UI Examples Readme Tool/org/eclipse/ui/examples/readmetool/ReadmeMarkerResolutionGenerator.java (status: 404)
Warning: Failed to fetch file for ID 5630
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.ui.examples.readmetool/Eclipse UI Examples Readme Tool/org/eclipse/ui/examples/readmetool/ReadmeMarkerResolutionGenerator.java (status: 404)
Warning: Failed to fetch file for ID 5631

Fetching code + source files: 4340it [24:36,  4.47it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_List.java (status: 404)
Warning: Failed to fetch file for ID 5632
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_List.java (status: 404)
Warning: Failed to fetch file for ID 5633

Fetching code + source files: 4351it [24:46,  1.49s/it]

Saved batch of 44 entries.

Fetching code + source files: 4374it [24:51,  4.39it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/views/navigator/NavigatorDropAdapter.java (status: 404)
Warning: Failed to fetch file for ID 5668

Fetching code + source files: 4400it [25:06,  2.07s/it]

Saved batch of 49 entries.

Fetching code + source files: 4403it [25:07,  1.09s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/perf/org.eclipse.linuxtools.perf/src/org/eclipse/linuxtools/internal/perf/PerfPlugin.java (status: 404)
Warning: Failed to fetch file for ID 5696
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/perf/org.eclipse.linuxtools.perf/src/org/eclipse/linuxtools/internal/perf/PerfPlugin.java (status: 404)
Warning: Failed to fetch file for ID 5697

Fetching code + source files: 4408it [25:08,  1.98it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/check/AnnotationCheckTreeNodeComparator.java (status: 404)
Warning: Failed to fetch file for ID 5702
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/check/AnnotationCheckTreeNodeComparator.java (status: 404)
Warning: Failed to fetch file for ID 5703

Fetching code + source files: 4420it [25:12,  3.79it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/WorkbenchPreferenceExtensionNode.java (status: 404)
Warning: Failed to fetch file for ID 5714
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/WorkbenchPreferenceExtensionNode.java (status: 404)
Warning: Failed to fetch file for ID 5715

Fetching code + source files: 4450it [25:27,  1.59s/it]

Saved batch of 44 entries.

Fetching code + source files: 4478it [25:33,  4.45it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/SSEUIMessages.java (status: 404)
Warning: Failed to fetch file for ID 5778
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/SSEUIMessages.java (status: 404)
Warning: Failed to fetch file for ID 5779

Fetching code + source files: 4498it [25:38,  4.10it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 5802

Fetching code + source files: 4501it [25:46,  1.25s/it]

Saved batch of 47 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 5803
Reached 4500 requests, sleeping for 1 hour ...

Fetching code + source files: 4506it [1:25:48, 236.90s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-common/org/eclipse/wst/xsd/ui/internal/common/commands/UpdateStringLengthFacetCommand.java (status: 404)
Warning: Failed to fetch file for ID 5808
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-common/org/eclipse/wst/xsd/ui/internal/common/commands/UpdateStringLengthFacetCommand.java (status: 404)
Warning: Failed to fetch file for ID 5809

Fetching code + source files: 4518it [1:25:51, 11.65s/it]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/metadata/src/org/apache/axis2/jaxws/description/impl/DescriptionFactoryImpl.java (status: 404)
Warning: Failed to fetch file for ID 5820
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/metadata/src/org/apache/axis2/jaxws/description/impl/DescriptionFactoryImpl.java (status: 404)
Warning: Failed to fetch file for ID 5821

Fetching code + source files: 4534it [1:25:56,  2.01it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-transport-jms/src/main/java/org/apache/axis/transport/jms/SimpleJMSListener.java (status: 404)
Warning: Failed to fetch file for ID 5838
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-transport-jms/src/main/java/org/apache/axis/transport/jms/SimpleJMSListener.java (status: 404)
Warning: Failed to fetch file for ID 5839

Fetching code + source files: 4542it [1:25:57,  3.84it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/preferences/GitDecoratorPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 5846
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/preferences/GitDecoratorPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 5847

Fetching code + source files: 4550it [1:26:07,  1.95s/it]

Saved batch of 41 entries.

Fetching code + source files: 4558it [1:26:09,  1.87it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-dictionary-lookup/src/main/java/org/apache/ctakes/dictionary/lookup/filter/MetaDataPostLookupFilterImpl.java (status: 404)
Warning: Failed to fetch file for ID 5864
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-dictionary-lookup/src/main/java/org/apache/ctakes/dictionary/lookup/filter/MetaDataPostLookupFilterImpl.java (status: 404)
Warning: Failed to fetch file for ID 5865

Fetching code + source files: 4563it [1:26:11,  3.10it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.core/src/org/eclipse/wst/xsl/core/model/Template.java (status: 404)
Warning: Failed to fetch file for ID 5870
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.core/src/org/eclipse/wst/xsl/core/model/Template.java (status: 404)
Warning: Failed to fetch file for ID 5871

Fetching code + source files: 4568it [1:26:12,  3.65it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/finddefinition/DefinitionFinder.java (status: 404)
Warning: Failed to fetch file for ID 5878
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/finddefinition/DefinitionFinder.java (status: 404)
Warning: Failed to fetch file for ID 5879

Fetching code + source files: 4591it [1:26:18,  4.72it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/transport/sshd/SshdSession.java (status: 404)
Warning: Failed to fetch file for ID 5910
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/transport/sshd/SshdSession.java (status: 404)
Warning: Failed to fetch file for ID 5911

Fetching code + source files: 4593it [1:26:18,  5.17it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.progress/src/org/eclipse/e4/ui/progress/internal/FinishedJobs.java (status: 404)
Warning: Failed to fetch file for ID 5912
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.progress/src/org/eclipse/e4/ui/progress/internal/FinishedJobs.java (status: 404)
Warning: Failed to fetch file for ID 5913

Fetching code + source files: 4601it [1:26:28,  1.84s/it]

Saved batch of 40 entries.

Fetching code + source files: 4650it [1:26:49,  1.74s/it]

Saved batch of 50 entries.

Fetching code + source files: 4653it [1:26:49,  1.02it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet263.java (status: 404)
Warning: Failed to fetch file for ID 5980
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet263.java (status: 404)
Warning: Failed to fetch file for ID 5981

Fetching code + source files: 4657it [1:26:50,  2.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/transport/PreUploadHook.java (status: 404)
Warning: Failed to fetch file for ID 5984
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/transport/PreUploadHook.java (status: 404)
Warning: Failed to fetch file for ID 5985

Fetching code + source files: 4701it [1:27:10,  1.59s/it]

Saved batch of 46 entries.

Fetching code + source files: 4713it [1:27:13,  3.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/core/search/matching/MatchLocatorParser.java (status: 404)
Warning: Failed to fetch file for ID 6059
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/core/search/matching/MatchLocatorParser.java (status: 404)
Warning: Failed to fetch file for ID 6060

Fetching code + source files: 4727it [1:27:17,  4.23it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/menus/WorkbenchMenuService.java (status: 404)
Warning: Failed to fetch file for ID 6077
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/menus/WorkbenchMenuService.java (status: 404)
Warning: Failed to fetch file for ID 6078

Fetching code + source files: 4741it [1:27:20,  3.76it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet305.java (status: 404)
Warning: Failed to fetch file for ID 6093
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet305.java (status: 404)
Warning: Failed to fetch file for ID 6094

Fetching code + source files: 4750it [1:27:31,  1.84s/it]

Saved batch of 44 entries.

Fetching code + source files: 4800it [1:27:52,  1.85s/it]

Saved batch of 50 entries.

Fetching code + source files: 4835it [1:28:00,  4.35it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/commands/IntegerConverter.java (status: 404)
Warning: Failed to fetch file for ID 6201
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/commands/IntegerConverter.java (status: 404)
Warning: Failed to fetch file for ID 6202

Fetching code + source files: 4841it [1:28:01,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/dom/properties/css2/ICSSPropertyPaddingHandler.java (status: 404)
Warning: Failed to fetch file for ID 6207
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/dom/properties/css2/ICSSPropertyPaddingHandler.java (status: 404)
Warning: Failed to fetch file for ID 6208

Fetching code + source files: 4847it [1:28:03,  4.80it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.dtd.ui/src/org/eclipse/wst/dtd/ui/internal/preferences/DTDTemplatePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 6217
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.dtd.ui/src/org/eclipse/wst/dtd/ui/internal/preferences/DTDTemplatePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 6218

Fetching code + source files: 4850it [1:28:12,  1.80s/it]

Saved batch of 44 entries.

Fetching code + source files: 4884it [1:28:21,  3.41it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/impl/dom/CSSValueListImpl.java (status: 404)
Warning: Failed to fetch file for ID 6262
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/impl/dom/CSSValueListImpl.java (status: 404)
Warning: Failed to fetch file for ID 6263

Fetching code + source files: 4894it [1:28:24,  3.39it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/transport/UploadPack.java (status: 404)
Warning: Failed to fetch file for ID 6272

Fetching code + source files: 4895it [1:28:24,  3.36it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui.test/src/org/eclipse/egit/ui/common/CompareEditorTester.java (status: 404)
Warning: Failed to fetch file for ID 6273

Fetching code + source files: 4901it [1:28:35,  1.56s/it]

Saved batch of 46 entries.

Fetching code + source files: 4903it [1:28:36,  1.05s/it]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 6283
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 6284

Fetching code + source files: 4909it [1:28:37,  2.45it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.executor/src/org/eclipse/titan/executor/executors/mctr/cli/CliExecutor.java (status: 404)
Warning: Failed to fetch file for ID 6289
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.executor/src/org/eclipse/titan/executor/executors/mctr/cli/CliExecutor.java (status: 404)
Warning: Failed to fetch file for ID 6290

Fetching code + source files: 4917it [1:28:39,  4.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanOctetString_Element.java (status: 404)
Warning: Failed to fetch file for ID 6297
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanOctetString_Element.java (status: 404)
Warning: Failed to fetch file for ID 6298

Fetching code + source files: 4921it [1:28:39,  4.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs/src/org/eclipse/jgit/lfs/lib/Constants.java (status: 404)
Warning: Failed to fetch file for ID 6301
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs/src/org/eclipse/jgit/lfs/lib/Constants.java (status: 404)
Warning: Failed to fetch file for ID 6302

Fetching code + source files: 4937it [1:28:44,  3.64it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/adapters/XSDWildcardAdapter.java (status: 404)
Warning: Failed to fetch file for ID 6317
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/adapters/XSDWildcardAdapter.java (status: 404)
Warning: Failed to fetch file for ID 6318

Fetching code + source files: 4950it [1:28:56,  2.43s/it]

Saved batch of 40 entries.

Fetching code + source files: 4961it [1:28:59,  2.81it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 6343
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 6344

Fetching code + source files: 4963it [1:28:59,  3.56it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 6347
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 6348

Fetching code + source files: 5000it [1:29:18,  1.94s/it]

Saved batch of 46 entries.

Fetching code + source files: 5008it [1:29:20,  2.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/nn/eval/EvaluationOfNeuralJointRelations.java (status: 404)
Warning: Failed to fetch file for ID 6395
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/nn/eval/EvaluationOfNeuralJointRelations.java (status: 404)
Warning: Failed to fetch file for ID 6396

Fetching code + source files: 5050it [1:29:41,  2.11s/it]

Saved batch of 48 entries.

Fetching code + source files: 5068it [1:29:46,  3.39it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/Snippet031TableViewerCustomTooltipsMultiSelection.java (status: 404)
Warning: Failed to fetch file for ID 6461
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/Snippet031TableViewerCustomTooltipsMultiSelection.java (status: 404)
Warning: Failed to fetch file for ID 6462

Fetching code + source files: 5070it [1:29:46,  4.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ActionExpression.java (status: 404)
Warning: Failed to fetch file for ID 6463
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ActionExpression.java (status: 404)
Warning: Failed to fetch file for ID 6464

Fetching code + source files: 5085it [1:29:50,  4.77it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/expressions/LegacyViewContributionExpression.java (status: 404)
Warning: Failed to fetch file for ID 6477
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/expressions/LegacyViewContributionExpression.java (status: 404)
Warning: Failed to fetch file for ID 6478

Fetching code + source files: 5101it [1:30:04,  1.57s/it]

Saved batch of 44 entries.

Fetching code + source files: 5151it [1:30:28,  1.83s/it]

Saved batch of 50 entries.

Fetching code + source files: 5165it [1:30:31,  4.07it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/util/Assert.java (status: 404)
Warning: Failed to fetch file for ID 6579
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/util/Assert.java (status: 404)
Warning: Failed to fetch file for ID 6580

Fetching code + source files: 5196it [1:30:39,  3.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.dataset/src/org/eclipse/nebula/widgets/nattable/dataset/generator/DataGenerator.java (status: 404)
Warning: Failed to fetch file for ID 6619
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.dataset/src/org/eclipse/nebula/widgets/nattable/dataset/generator/DataGenerator.java (status: 404)
Warning: Failed to fetch file for ID 6620

Fetching code + source files: 5201it [1:30:50,  2.12s/it]

Saved batch of 46 entries.

Fetching code + source files: 5214it [1:30:54,  3.64it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormHeading.java (status: 404)
Warning: Failed to fetch file for ID 6645
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormHeading.java (status: 404)
Warning: Failed to fetch file for ID 6646

Fetching code + source files: 5236it [1:30:59,  4.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 6669
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 6670

Fetching code + source files: 5244it [1:31:01,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/oprofile/org.eclipse.linuxtools.oprofile.core/src/org/eclipse/linuxtools/internal/oprofile/core/opxml/info/EventListProcessor.java (status: 404)
Warning: Failed to fetch file for ID 6677
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/oprofile/org.eclipse.linuxtools.oprofile.core/src/org/eclipse/linuxtools/internal/oprofile/core/opxml/info/EventListProcessor.java (status: 404)
Warning: Failed to fetch file for ID 6678

Fetching code + source files: 5251it [1:31:12,  1.76s/it]

Saved batch of 44 entries.

Fetching code + source files: 5284it [1:31:21,  3.82it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/udp/src/main/java/org/apache/axis2/transport/udp/UDPOutTransportInfo.java (status: 404)
Warning: Failed to fetch file for ID 6721
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/udp/src/main/java/org/apache/axis2/transport/udp/UDPOutTransportInfo.java (status: 404)
Warning: Failed to fetch file for ID 6722

Fetching code + source files: 5301it [1:31:36,  1.69s/it]

Saved batch of 48 entries.

Fetching code + source files: 5318it [1:31:40,  3.70it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.core/src/org/eclipse/wst/html/core/internal/HTMLContentBuilder.java (status: 404)
Warning: Failed to fetch file for ID 6759
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.core/src/org/eclipse/wst/html/core/internal/HTMLContentBuilder.java (status: 404)
Warning: Failed to fetch file for ID 6760

Fetching code + source files: 5351it [1:31:58,  1.93s/it]

Saved batch of 48 entries.

Fetching code + source files: 5394it [1:32:08,  4.68it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/soapmonitor/servlet/src/main/java/org/apache/axis2/soapmonitor/applet/SOAPMonitorApplet.java (status: 404)
Warning: Failed to fetch file for ID 6849
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/soapmonitor/servlet/src/main/java/org/apache/axis2/soapmonitor/applet/SOAPMonitorApplet.java (status: 404)
Warning: Failed to fetch file for ID 6850

Fetching code + source files: 5401it [1:32:21,  1.60s/it]

Saved batch of 48 entries.

Fetching code + source files: 5404it [1:32:22,  1.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/DataAssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 6859
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/DataAssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 6860

Fetching code + source files: 5451it [1:32:44,  1.80s/it]

Saved batch of 48 entries.

Fetching code + source files: 5499it [1:32:56,  4.85it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs.server/src/org/eclipse/jgit/lfs/server/TransferHandler.java (status: 404)
Warning: Failed to fetch file for ID 6971
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs.server/src/org/eclipse/jgit/lfs/server/TransferHandler.java (status: 404)
Warning: Failed to fetch file for ID 6972

Fetching code + source files: 5501it [1:33:09,  2.25s/it]

Saved batch of 48 entries.

Fetching code + source files: 5551it [1:33:35,  2.76s/it]

Saved batch of 50 entries.

Fetching code + source files: 5600it [1:33:59,  2.24s/it]

Saved batch of 50 entries.

Fetching code + source files: 5604it [1:34:00,  1.09s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/activities/Activity.java (status: 404)
Warning: Failed to fetch file for ID 7091
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/activities/Activity.java (status: 404)
Warning: Failed to fetch file for ID 7092

Fetching code + source files: 5607it [1:34:00,  1.63it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/editors/configeditor/pages/include/DefineDataContentProvider.java (status: 404)
Warning: Failed to fetch file for ID 7093
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/editors/configeditor/pages/include/DefineDataContentProvider.java (status: 404)
Warning: Failed to fetch file for ID 7094

Fetching code + source files: 5636it [1:34:08,  4.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/impl/ApplicationImpl.java (status: 404)
Warning: Failed to fetch file for ID 7125
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/impl/ApplicationImpl.java (status: 404)
Warning: Failed to fetch file for ID 7126

Fetching code + source files: 5648it [1:34:11,  3.30it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/json/bundles/org.eclipse.wst.json.core/src/org/eclipse/wst/json/core/internal/format/JSONArrayFormatter.java (status: 404)
Warning: Failed to fetch file for ID 7147

Fetching code + source files: 5651it [1:34:23,  2.04s/it]

Saved batch of 43 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/json/bundles/org.eclipse.wst.json.core/src/org/eclipse/wst/json/core/internal/format/JSONArrayFormatter.java (status: 404)
Warning: Failed to fetch file for ID 7148

Fetching code + source files: 5668it [1:34:28,  3.75it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/function/ExtractToFunctionWizardParamsPage.java (status: 404)
Warning: Failed to fetch file for ID 7167
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/function/ExtractToFunctionWizardParamsPage.java (status: 404)
Warning: Failed to fetch file for ID 7168

Fetching code + source files: 5674it [1:34:29,  4.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/WSDL2Useless.java (status: 404)
Warning: Failed to fetch file for ID 7175
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/WSDL2Useless.java (status: 404)
Warning: Failed to fetch file for ID 7176

Fetching code + source files: 5689it [1:34:33,  4.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/embedder/AbstractRunnable.java (status: 404)
Warning: Failed to fetch file for ID 7191
Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/embedder/AbstractRunnable.java (status: 404)
Warning: Failed to fetch file for ID 7192

Fetching code + source files: 5693it [1:34:33,  5.10it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/tests/org.eclipse.wst.jsdt.web.core.tests/src/org/eclipse/wst/jsdt/web/core/tests/translation/TestHtmlTranslation.java (status: 404)
Warning: Failed to fetch file for ID 7195
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/tests/org.eclipse.wst.jsdt.web.core.tests/src/org/eclipse/wst/jsdt/web/core/tests/translation/TestHtmlTranslation.java (status: 404)
Warning: Failed to fetch file for ID 7196

Fetching code + source files: 5698it [1:34:35,  4.23it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/extractors/TestCaseEventDispatcher.java (status: 404)
Warning: Failed to fetch file for ID 7205

Fetching code + source files: 5701it [1:34:47,  1.90s/it]

Saved batch of 40 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/extractors/TestCaseEventDispatcher.java (status: 404)
Warning: Failed to fetch file for ID 7206

Fetching code + source files: 5717it [1:34:51,  3.81it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/typehierarchy/ToggleViewAction.java (status: 404)
Warning: Failed to fetch file for ID 7221
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/typehierarchy/ToggleViewAction.java (status: 404)
Warning: Failed to fetch file for ID 7222

Fetching code + source files: 5725it [1:34:54,  2.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-relation-extractor/src/main/java/org/apache/ctakes/relationextractor/ae/baselines/Baseline2EntityMentionPairRelationExtractorAnnotator.java (status: 404)
Warning: Failed to fetch file for ID 7229
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-relation-extractor/src/main/java/org/apache/ctakes/relationextractor/ae/baselines/Baseline2EntityMentionPairRelationExtractorAnnotator.java (status: 404)
Warning: Failed to fetch file for ID 7230

Fetching code + source files: 5731it [1:34:56,  3.62it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/pipeline/GenerateSentenceBIODescriptors.java (status: 404)
Warning: Failed to fetch file for ID 7235
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/pipeline/GenerateSentenceBIODescriptors.java (status: 404)
Warning: Failed to fetch file for ID 7236

Fetching code + source files: 5751it [1:35:12,  1.79s/it]

Saved batch of 43 entries.

Fetching code + source files: 5786it [1:35:21,  4.16it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/handlers/ShowPerspectiveHandler.java (status: 404)
Warning: Failed to fetch file for ID 7305
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/handlers/ShowPerspectiveHandler.java (status: 404)
Warning: Failed to fetch file for ID 7306

Fetching code + source files: 5801it [1:35:37,  2.33s/it]

Saved batch of 48 entries.

Fetching code + source files: 5804it [1:35:37,  1.02s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/ElementReferenceRenderer.java (status: 404)
Warning: Failed to fetch file for ID 7327
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/ElementReferenceRenderer.java (status: 404)
Warning: Failed to fetch file for ID 7328

Fetching code + source files: 5819it [1:35:41,  4.29it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/emulated/expand/org/eclipse/swt/widgets/ExpandItem.java (status: 404)
Warning: Failed to fetch file for ID 7345
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/emulated/expand/org/eclipse/swt/widgets/ExpandItem.java (status: 404)
Warning: Failed to fetch file for ID 7346

Fetching code + source files: 5824it [1:35:42,  3.96it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/fieldassist/ContentProposalAdapter.java (status: 404)
Warning: Failed to fetch file for ID 7353
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/fieldassist/ContentProposalAdapter.java (status: 404)
Warning: Failed to fetch file for ID 7354

Fetching code + source files: 5851it [1:36:00,  1.71s/it]

Saved batch of 44 entries.

Fetching code + source files: 5898it [1:36:12,  3.73it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/NeuralEventTimeRelationsEvaluation.java (status: 404)
Warning: Failed to fetch file for ID 7439

Fetching code + source files: 5901it [1:36:24,  2.04s/it]

Saved batch of 49 entries.
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/NeuralEventTimeRelationsEvaluation.java (status: 404)
Warning: Failed to fetch file for ID 7440

Fetching code + source files: 5908it [1:36:26,  2.16it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/statements/While_Statement.java (status: 404)
Warning: Failed to fetch file for ID 7447
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/statements/While_Statement.java (status: 404)
Warning: Failed to fetch file for ID 7448

Fetching code + source files: 5921it [1:36:29,  4.34it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 7461
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 7462

Fetching code + source files: 5924it [1:36:30,  4.10it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.core.tests/src/org/eclipse/dltk/core/tests/ProjectSetup.java (status: 404)
Warning: Failed to fetch file for ID 7465
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.core.tests/src/org/eclipse/dltk/core/tests/ProjectSetup.java (status: 404)
Warning: Failed to fetch file for ID 7466

Fetching code + source files: 5948it [1:36:36,  3.87it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/IType.java (status: 404)
Warning: Failed to fetch file for ID 7495

Fetching code + source files: 5951it [1:36:49,  1.76s/it]

Saved batch of 42 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/IType.java (status: 404)
Warning: Failed to fetch file for ID 7496

Fetching code + source files: 6001it [1:37:13,  2.43s/it]

Saved batch of 49 entries.

Fetching code + source files: 6002it [1:37:14,  1.88s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests/src/org/eclipse/jface/widgets/TestUnitTextFactory.java (status: 404)
Warning: Failed to fetch file for ID 7557
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests/src/org/eclipse/jface/widgets/TestUnitTextFactory.java (status: 404)
Warning: Failed to fetch file for ID 7558

Fetching code + source files: 6005it [1:37:14,  1.12it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/rule/ComposedRuleElement.java (status: 404)
Warning: Failed to fetch file for ID 7559
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/rule/ComposedRuleElement.java (status: 404)
Warning: Failed to fetch file for ID 7560

Fetching code + source files: 6008it [1:37:15,  1.87it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/condition/CountCondition.java (status: 404)
Warning: Failed to fetch file for ID 7563
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/condition/CountCondition.java (status: 404)
Warning: Failed to fetch file for ID 7564

Fetching code + source files: 6011it [1:37:15,  3.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/contentassist/CompoundContentAssistProcessor.java (status: 404)
Warning: Failed to fetch file for ID 7565
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/contentassist/CompoundContentAssistProcessor.java (status: 404)
Warning: Failed to fetch file for ID 7566

Fetching code + source files: 6022it [1:37:18,  3.86it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/ketch/RemoteGitReplica.java (status: 404)
Warning: Failed to fetch file for ID 7577
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/ketch/RemoteGitReplica.java (status: 404)
Warning: Failed to fetch file for ID 7578

Fetching code + source files: 6049it [1:37:25,  4.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.archive/src/org/eclipse/jgit/archive/FormatActivator.java (status: 404)
Warning: Failed to fetch file for ID 7609

Fetching code + source files: 6051it [1:37:38,  2.24s/it]

Saved batch of 39 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.archive/src/org/eclipse/jgit/archive/FormatActivator.java (status: 404)
Warning: Failed to fetch file for ID 7610

Fetching code + source files: 6062it [1:37:41,  2.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt/org/eclipse/wst/xsd/ui/internal/adt/design/editparts/BaseEditPart.java (status: 404)
Warning: Failed to fetch file for ID 7621
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt/org/eclipse/wst/xsd/ui/internal/adt/design/editparts/BaseEditPart.java (status: 404)
Warning: Failed to fetch file for ID 7622

Fetching code + source files: 6072it [1:37:44,  3.88it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyOuterKeylineSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 7631
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyOuterKeylineSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 7632

Fetching code + source files: 6082it [1:37:47,  4.02it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/emulated/taskbar/org/eclipse/swt/widgets/TaskBar.java (status: 404)
Warning: Failed to fetch file for ID 7643
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/emulated/taskbar/org/eclipse/swt/widgets/TaskBar.java (status: 404)
Warning: Failed to fetch file for ID 7644

Fetching code + source files: 6101it [1:38:04,  2.53s/it]

Saved batch of 43 entries.

Fetching code + source files: 6119it [1:38:08,  4.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/value/SimpleValueProperty.java (status: 404)
Warning: Failed to fetch file for ID 7681
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/value/SimpleValueProperty.java (status: 404)
Warning: Failed to fetch file for ID 7682

Fetching code + source files: 6151it [1:38:29,  2.42s/it]

Saved batch of 48 entries.

Fetching code + source files: 6158it [1:38:31,  1.70it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.console.ui/src/org/eclipse/dltk/console/ui/ScriptConsolePartitioner.java (status: 404)
Warning: Failed to fetch file for ID 7723
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.console.ui/src/org/eclipse/dltk/console/ui/ScriptConsolePartitioner.java (status: 404)
Warning: Failed to fetch file for ID 7724

Fetching code + source files: 6165it [1:38:33,  2.90it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/cleartk/SumContext.java (status: 404)
Warning: Failed to fetch file for ID 7730

Fetching code + source files: 6201it [1:38:54,  2.26s/it]

Saved batch of 47 entries.

Fetching code + source files: 6214it [1:38:57,  3.44it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/launch/ClasspathEntry.java (status: 404)
Warning: Failed to fetch file for ID 7791
Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/launch/ClasspathEntry.java (status: 404)
Warning: Failed to fetch file for ID 7792

Fetching code + source files: 6220it [1:38:58,  3.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug499850_VirtualTableHang.java (status: 404)
Warning: Failed to fetch file for ID 7799
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug499850_VirtualTableHang.java (status: 404)
Warning: Failed to fetch file for ID 7800

Fetching code + source files: 6251it [1:39:18,  1.95s/it]

Saved batch of 46 entries.

Fetching code + source files: 6254it [1:39:19,  1.01s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/pom/MavenPomEditor.java (status: 404)
Warning: Failed to fetch file for ID 7837
Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/pom/MavenPomEditor.java (status: 404)
Warning: Failed to fetch file for ID 7838

Fetching code + source files: 6286it [1:39:27,  4.66it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 7881
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 7882

Fetching code + source files: 6301it [1:39:43,  2.28s/it]

Saved batch of 46 entries.

Fetching code + source files: 6350it [1:40:08,  2.17s/it]

Saved batch of 50 entries.

Fetching code + source files: 6352it [1:40:08,  1.58s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/Boolean_Type.java (status: 404)
Warning: Failed to fetch file for ID 7953
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/Boolean_Type.java (status: 404)
Warning: Failed to fetch file for ID 7954

Fetching code + source files: 6356it [1:40:09,  1.17it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.gitflow/src/org/eclipse/egit/gitflow/op/FeatureCheckoutOperation.java (status: 404)
Warning: Failed to fetch file for ID 7959
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.gitflow/src/org/eclipse/egit/gitflow/op/FeatureCheckoutOperation.java (status: 404)
Warning: Failed to fetch file for ID 7960

Fetching code + source files: 6367it [1:40:12,  4.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/WorkbenchPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 7969
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/WorkbenchPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 7970

Fetching code + source files: 6401it [1:40:33,  2.16s/it]

Saved batch of 44 entries.

Fetching code + source files: 6425it [1:40:39,  4.66it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/set/UnionSetProperty.java (status: 404)
Warning: Failed to fetch file for ID 8033
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/set/UnionSetProperty.java (status: 404)
Warning: Failed to fetch file for ID 8034

Fetching code + source files: 6448it [1:40:45,  3.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/wsdl/SkeletonImpl.java (status: 404)
Warning: Failed to fetch file for ID 8067

Fetching code + source files: 6451it [1:40:59,  2.26s/it]

Saved batch of 47 entries.
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/wsdl/SkeletonImpl.java (status: 404)
Warning: Failed to fetch file for ID 8068

Fetching code + source files: 6475it [1:41:05,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/expression/number/NumberFeatureExpression.java (status: 404)
Warning: Failed to fetch file for ID 8099
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/expression/number/NumberFeatureExpression.java (status: 404)
Warning: Failed to fetch file for ID 8100

Fetching code + source files: 6496it [1:41:11,  3.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/util/AbstractCssTraverser.java (status: 404)
Warning: Failed to fetch file for ID 8127
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/util/AbstractCssTraverser.java (status: 404)
Warning: Failed to fetch file for ID 8128

Fetching code + source files: 6501it [1:41:25,  1.93s/it]

Saved batch of 45 entries.

Fetching code + source files: 6550it [1:41:50,  2.43s/it]

Saved batch of 50 entries.

Fetching code + source files: 6568it [1:41:54,  3.64it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/MarkerHandler.java (status: 404)
Warning: Failed to fetch file for ID 8217
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/MarkerHandler.java (status: 404)
Warning: Failed to fetch file for ID 8218

Fetching code + source files: 6584it [1:41:58,  4.32it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/ParsedActualParameters.java (status: 404)
Warning: Failed to fetch file for ID 8235
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/ParsedActualParameters.java (status: 404)
Warning: Failed to fetch file for ID 8236

Fetching code + source files: 6590it [1:41:59,  4.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/nn/data/GoldEventPrinterWithLabels.java (status: 404)
Warning: Failed to fetch file for ID 8241
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/nn/data/GoldEventPrinterWithLabels.java (status: 404)
Warning: Failed to fetch file for ID 8242

Fetching code + source files: 6601it [1:42:16,  2.09s/it]

Saved batch of 44 entries.

Fetching code + source files: 6628it [1:42:23,  4.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/data/ExtendedReflectiveColumnPropertyAccessor.java (status: 404)
Warning: Failed to fetch file for ID 8285
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/data/ExtendedReflectiveColumnPropertyAccessor.java (status: 404)
Warning: Failed to fetch file for ID 8286

Fetching code + source files: 6646it [1:42:27,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/examples/org.eclipse.rap.demo/src/org/eclipse/rap/demo/DemoChartViewPart.java (status: 404)
Warning: Failed to fetch file for ID 8303
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/examples/org.eclipse.rap.demo/src/org/eclipse/rap/demo/DemoChartViewPart.java (status: 404)
Warning: Failed to fetch file for ID 8304

Fetching code + source files: 6651it [1:42:42,  1.90s/it]

Saved batch of 46 entries.

Fetching code + source files: 6662it [1:42:44,  3.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/paint/TextTool.java (status: 404)
Warning: Failed to fetch file for ID 8319
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/paint/TextTool.java (status: 404)
Warning: Failed to fetch file for ID 8320

Fetching code + source files: 6680it [1:42:48,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/utils/org/eclipse/dltk/utils/TextUtils.java (status: 404)
Warning: Failed to fetch file for ID 8343
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/utils/org/eclipse/dltk/utils/TextUtils.java (status: 404)
Warning: Failed to fetch file for ID 8344

Fetching code + source files: 6698it [1:42:52,  4.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/DialogCellEditor.java (status: 404)
Warning: Failed to fetch file for ID 8365

Fetching code + source files: 6701it [1:43:07,  2.10s/it]

Saved batch of 45 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/DialogCellEditor.java (status: 404)
Warning: Failed to fetch file for ID 8366

Fetching code + source files: 6708it [1:43:09,  1.86it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 8375
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 8376

Fetching code + source files: 6716it [1:43:11,  3.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/builder/BPMN2Builder.java (status: 404)
Warning: Failed to fetch file for ID 8383
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/builder/BPMN2Builder.java (status: 404)
Warning: Failed to fetch file for ID 8384

Fetching code + source files: 6734it [1:43:15,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/menus/ActionSet.java (status: 404)
Warning: Failed to fetch file for ID 8401
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/menus/ActionSet.java (status: 404)
Warning: Failed to fetch file for ID 8402

Fetching code + source files: 6751it [1:43:33,  2.91s/it]

Saved batch of 43 entries.

Fetching code + source files: 6767it [1:43:37,  4.40it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ContainerEnvironmentVariableDialog.java (status: 404)
Warning: Failed to fetch file for ID 8443
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.ui/src/org/eclipse/linuxtools/internal/docker/ui/wizards/ContainerEnvironmentVariableDialog.java (status: 404)
Warning: Failed to fetch file for ID 8444

Fetching code + source files: 6790it [1:43:43,  4.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 8467
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 8468

Fetching code + source files: 6798it [1:43:45,  3.85it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-ytex/src/main/java/org/apache/ctakes/ytex/kernel/model/FeatureRank.java (status: 404)
Warning: Failed to fetch file for ID 8477

Fetching code + source files: 6801it [1:44:00,  2.40s/it]

Saved batch of 45 entries.
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-ytex/src/main/java/org/apache/ctakes/ytex/kernel/model/FeatureRank.java (status: 404)
Warning: Failed to fetch file for ID 8478

Fetching code + source files: 6820it [1:44:04,  4.03it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/util/VisualTextDirectionSegmentListener.java (status: 404)
Warning: Failed to fetch file for ID 8499
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/util/VisualTextDirectionSegmentListener.java (status: 404)
Warning: Failed to fetch file for ID 8500

Fetching code + source files: 6851it [1:44:26,  2.53s/it]

Saved batch of 47 entries.

Fetching code + source files: 6876it [1:44:32,  4.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ObjectContributorManager.java (status: 404)
Warning: Failed to fetch file for ID 8557
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ObjectContributorManager.java (status: 404)
Warning: Failed to fetch file for ID 8558

Fetching code + source files: 6892it [1:44:36,  4.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.dtd.core/emfmodel/org/eclipse/wst/dtd/core/internal/emf/impl/DTDExternalEntityImpl.java (status: 404)
Warning: Failed to fetch file for ID 8575
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.dtd.core/emfmodel/org/eclipse/wst/dtd/core/internal/emf/impl/DTDExternalEntityImpl.java (status: 404)
Warning: Failed to fetch file for ID 8576

Fetching code + source files: 6898it [1:44:37,  4.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.navigator/src/org/eclipse/ui/internal/navigator/wizards/WizardShortcutAction.java (status: 404)
Warning: Failed to fetch file for ID 8581
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.navigator/src/org/eclipse/ui/internal/navigator/wizards/WizardShortcutAction.java (status: 404)
Warning: Failed to fetch file for ID 8582

Fetching code + source files: 6901it [1:44:52,  2.28s/it]

Saved batch of 44 entries.

Fetching code + source files: 6907it [1:44:54,  1.81it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 8589
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 8590

Fetching code + source files: 6925it [1:44:58,  4.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/PreGenRecordOf.java (status: 404)
Warning: Failed to fetch file for ID 8607
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/PreGenRecordOf.java (status: 404)
Warning: Failed to fetch file for ID 8608

Fetching code + source files: 6951it [1:45:20,  2.33s/it]

Saved batch of 46 entries.

Fetching code + source files: 6958it [1:45:21,  2.02it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-transport-jms/src/main/java/org/apache/axis/transport/jms/JMSEndpoint.java (status: 404)
Warning: Failed to fetch file for ID 8651
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-transport-jms/src/main/java/org/apache/axis/transport/jms/JMSEndpoint.java (status: 404)
Warning: Failed to fetch file for ID 8652

Fetching code + source files: 6974it [1:45:25,  4.12it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.launch/src/org/eclipse/linuxtools/internal/valgrind/launch/ValgrindOptionsTab.java (status: 404)
Warning: Failed to fetch file for ID 8669
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.launch/src/org/eclipse/linuxtools/internal/valgrind/launch/ValgrindOptionsTab.java (status: 404)
Warning: Failed to fetch file for ID 8670

Fetching code + source files: 6989it [1:45:29,  4.73it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug531667_GC_transform_is_wrong.java (status: 404)
Warning: Failed to fetch file for ID 8683
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug531667_GC_transform_is_wrong.java (status: 404)
Warning: Failed to fetch file for ID 8684

Fetching code + source files: 7001it [1:45:47,  2.28s/it]

Saved batch of 44 entries.

Fetching code + source files: 7051it [1:46:17,  2.19s/it]

Saved batch of 50 entries.

Fetching code + source files: 7062it [1:46:20,  2.65it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt.tools/JNI Generation/org/eclipse/swt/tools/internal/LockGenerator.java (status: 404)
Warning: Failed to fetch file for ID 8769
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt.tools/JNI Generation/org/eclipse/swt/tools/internal/LockGenerator.java (status: 404)
Warning: Failed to fetch file for ID 8770

Fetching code + source files: 7085it [1:46:25,  5.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/property/JbpmIoParametersListComposite.java (status: 404)
Warning: Failed to fetch file for ID 8791
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/property/JbpmIoParametersListComposite.java (status: 404)
Warning: Failed to fetch file for ID 8792

Fetching code + source files: 7098it [1:46:28,  4.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/IncludeTransform.java (status: 404)
Warning: Failed to fetch file for ID 8815

Fetching code + source files: 7101it [1:46:44,  2.13s/it]

Saved batch of 45 entries.
Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/IncludeTransform.java (status: 404)
Warning: Failed to fetch file for ID 8816

Fetching code + source files: 7130it [1:46:51,  4.44it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/PreGenRecordOf.java (status: 404)
Warning: Failed to fetch file for ID 8847
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/PreGenRecordOf.java (status: 404)
Warning: Failed to fetch file for ID 8848

Fetching code + source files: 7146it [1:46:55,  4.15it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/DateTime.java (status: 404)
Warning: Failed to fetch file for ID 8865
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/DateTime.java (status: 404)
Warning: Failed to fetch file for ID 8866

Fetching code + source files: 7151it [1:47:11,  2.79s/it]

Saved batch of 45 entries.

Fetching code + source files: 7173it [1:47:16,  4.51it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-transport-jms/src/main/java/org/apache/axis/transport/jms/TopicConnector.java (status: 404)
Warning: Failed to fetch file for ID 8895
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-transport-jms/src/main/java/org/apache/axis/transport/jms/TopicConnector.java (status: 404)
Warning: Failed to fetch file for ID 8896

Fetching code + source files: 7186it [1:47:19,  4.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.core/src/org/eclipse/wst/xsl/core/internal/validation/XSLValidationMessage.java (status: 404)
Warning: Failed to fetch file for ID 8909
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.core/src/org/eclipse/wst/xsl/core/internal/validation/XSLValidationMessage.java (status: 404)
Warning: Failed to fetch file for ID 8910

Fetching code + source files: 7189it [1:47:20,  4.95it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/profiling/org.eclipse.linuxtools.dataviewers/src/org/eclipse/linuxtools/dataviewers/actions/STExpandAllTreeAction.java (status: 404)
Warning: Failed to fetch file for ID 8911
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/profiling/org.eclipse.linuxtools.dataviewers/src/org/eclipse/linuxtools/dataviewers/actions/STExpandAllTreeAction.java (status: 404)
Warning: Failed to fetch file for ID 8912

Fetching code + source files: 7201it [1:47:38,  2.75s/it]

Saved batch of 44 entries.

Fetching code + source files: 7203it [1:47:38,  1.61s/it]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/rule/quantifier/QuestionGreedy.java (status: 404)
Warning: Failed to fetch file for ID 8927
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/rule/quantifier/QuestionGreedy.java (status: 404)
Warning: Failed to fetch file for ID 8928

Fetching code + source files: 7205it [1:47:39,  1.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/provisional/wizards/GitRepositoryInfo.java (status: 404)
Warning: Failed to fetch file for ID 8929
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/provisional/wizards/GitRepositoryInfo.java (status: 404)
Warning: Failed to fetch file for ID 8930

Fetching code + source files: 7214it [1:47:41,  3.46it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java (status: 404)
Warning: Failed to fetch file for ID 8941
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java (status: 404)
Warning: Failed to fetch file for ID 8942

Fetching code + source files: 7217it [1:47:42,  4.36it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/accessibility/CTable.java (status: 404)
Warning: Failed to fetch file for ID 8943
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/accessibility/CTable.java (status: 404)
Warning: Failed to fetch file for ID 8944

Fetching code + source files: 7220it [1:47:43,  4.04it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/TestViewerConfigurationDTD.java (status: 404)
Warning: Failed to fetch file for ID 8947
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/TestViewerConfigurationDTD.java (status: 404)
Warning: Failed to fetch file for ID 8948

Fetching code + source files: 7223it [1:47:43,  4.88it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/push/PushResultTable.java (status: 404)
Warning: Failed to fetch file for ID 8949
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/push/PushResultTable.java (status: 404)
Warning: Failed to fetch file for ID 8950

Fetching code + source files: 7240it [1:47:47,  4.37it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/BitSet.java (status: 404)
Warning: Failed to fetch file for ID 8969
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/BitSet.java (status: 404)
Warning: Failed to fetch file for ID 8970

Fetching code + source files: 7251it [1:48:05,  2.84s/it]

Saved batch of 36 entries.

Fetching code + source files: 7260it [1:48:07,  2.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/design/editparts/XSDSimpleTypeEditPart.java (status: 404)
Warning: Failed to fetch file for ID 8993
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/design/editparts/XSDSimpleTypeEditPart.java (status: 404)
Warning: Failed to fetch file for ID 8994

Fetching code + source files: 7294it [1:48:16,  4.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/self-service/src/main/java/com/epam/dlab/backendapi/dao/BillingDAO.java (status: 404)
Warning: Failed to fetch file for ID 9034
Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/self-service/src/main/java/com/epam/dlab/backendapi/dao/BillingDAO.java (status: 404)
Warning: Failed to fetch file for ID 9035

Fetching code + source files: 7298it [1:48:17,  3.88it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/action/GetFeatureAction.java (status: 404)
Warning: Failed to fetch file for ID 9040

Fetching code + source files: 7301it [1:48:32,  2.55s/it]

Saved batch of 45 entries.
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/action/GetFeatureAction.java (status: 404)
Warning: Failed to fetch file for ID 9041

Fetching code + source files: 7305it [1:48:33,  1.10it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/property/JbpmSequenceFlowPropertySection.java (status: 404)
Warning: Failed to fetch file for ID 9046
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/property/JbpmSequenceFlowPropertySection.java (status: 404)
Warning: Failed to fetch file for ID 9047

Fetching code + source files: 7309it [1:48:34,  2.67it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.formatter/src/org/eclipse/dltk/formatter/AbstractScriptFormatterFactory.java (status: 404)
Warning: Failed to fetch file for ID 9050
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.formatter/src/org/eclipse/dltk/formatter/AbstractScriptFormatterFactory.java (status: 404)
Warning: Failed to fetch file for ID 9051

Fetching code + source files: 7318it [1:48:36,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/Label.java (status: 404)
Warning: Failed to fetch file for ID 9064
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/Label.java (status: 404)
Warning: Failed to fetch file for ID 9065

Fetching code + source files: 7350it [1:48:59,  3.44s/it]

Saved batch of 43 entries.

Fetching code + source files: 7353it [1:49:00,  1.60s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.e4.ui.menu.tests.p1/src/org/eclipse/e4/ui/menu/tests/p1/Activator.java (status: 404)
Warning: Failed to fetch file for ID 9104
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.e4.ui.menu.tests.p1/src/org/eclipse/e4/ui/menu/tests/p1/Activator.java (status: 404)
Warning: Failed to fetch file for ID 9105

Fetching code + source files: 7355it [1:49:00,  1.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.jst.jsp.core/src/org/eclipse/jst/jsp/core/internal/Logger.java (status: 404)
Warning: Failed to fetch file for ID 9106
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.jst.jsp.core/src/org/eclipse/jst/jsp/core/internal/Logger.java (status: 404)
Warning: Failed to fetch file for ID 9107

Fetching code + source files: 7357it [1:49:01,  1.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanValue_Array.java (status: 404)
Warning: Failed to fetch file for ID 9108
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanValue_Array.java (status: 404)
Warning: Failed to fetch file for ID 9109

Fetching code + source files: 7386it [1:49:08,  4.27it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/core/search/SearchPattern.java (status: 404)
Warning: Failed to fetch file for ID 9144
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/core/search/SearchPattern.java (status: 404)
Warning: Failed to fetch file for ID 9145

Fetching code + source files: 7396it [1:49:10,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/DeltaTask.java (status: 404)
Warning: Failed to fetch file for ID 9154
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/DeltaTask.java (status: 404)
Warning: Failed to fetch file for ID 9155

Fetching code + source files: 7401it [1:49:26,  2.89s/it]

Saved batch of 40 entries.

Fetching code + source files: 7451it [1:49:54,  2.99s/it]

Saved batch of 50 entries.

Fetching code + source files: 7491it [1:50:03,  4.83it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/PreGenRecordOf.java (status: 404)
Warning: Failed to fetch file for ID 9262
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/PreGenRecordOf.java (status: 404)
Warning: Failed to fetch file for ID 9263

Fetching code + source files: 7501it [1:50:21,  2.41s/it]

Saved batch of 48 entries.

Fetching code + source files: 7551it [1:50:50,  2.79s/it]

Saved batch of 50 entries.

Fetching code + source files: 7553it [1:50:50,  1.65s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.browser/src/org/eclipse/ui/internal/browser/BusyIndicator.java (status: 404)
Warning: Failed to fetch file for ID 9330
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.browser/src/org/eclipse/ui/internal/browser/BusyIndicator.java (status: 404)
Warning: Failed to fetch file for ID 9331

Fetching code + source files: 7555it [1:50:50,  1.05it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/painter/cell/GraphicsUtils.java (status: 404)
Warning: Failed to fetch file for ID 9332
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/painter/cell/GraphicsUtils.java (status: 404)
Warning: Failed to fetch file for ID 9333

Fetching code + source files: 7601it [1:51:17,  2.08s/it]

Saved batch of 46 entries.

Fetching code + source files: 7609it [1:51:19,  2.46it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/launchConfigurations/InterpreterTab.java (status: 404)
Warning: Failed to fetch file for ID 9392
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/launchConfigurations/InterpreterTab.java (status: 404)
Warning: Failed to fetch file for ID 9393

Fetching code + source files: 7634it [1:51:25,  4.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.testing/src/org/eclipse/dltk/testing/AbstractTestingEngine.java (status: 404)
Warning: Failed to fetch file for ID 9420
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.testing/src/org/eclipse/dltk/testing/AbstractTestingEngine.java (status: 404)
Warning: Failed to fetch file for ID 9421

Fetching code + source files: 7651it [1:51:45,  2.34s/it]

Saved batch of 46 entries.

Fetching code + source files: 7669it [1:51:49,  4.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/wizard/Snippet071WizardWithProgressAndCancel.java (status: 404)
Warning: Failed to fetch file for ID 9468
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/wizard/Snippet071WizardWithProgressAndCancel.java (status: 404)
Warning: Failed to fetch file for ID 9469

Fetching code + source files: 7672it [1:51:50,  3.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/EditorMenuManager.java (status: 404)
Warning: Failed to fetch file for ID 9472
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/EditorMenuManager.java (status: 404)
Warning: Failed to fetch file for ID 9473

Fetching code + source files: 7701it [1:52:13,  2.54s/it]

Saved batch of 46 entries.

Fetching code + source files: 7734it [1:52:21,  4.32it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java (status: 404)
Warning: Failed to fetch file for ID 9541
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java (status: 404)
Warning: Failed to fetch file for ID 9542

Fetching code + source files: 7736it [1:52:22,  4.37it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-ytex/src/main/java/org/apache/ctakes/ytex/kernel/SparseDataExporterImpl.java (status: 404)
Warning: Failed to fetch file for ID 9543
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-ytex/src/main/java/org/apache/ctakes/ytex/kernel/SparseDataExporterImpl.java (status: 404)
Warning: Failed to fetch file for ID 9544

Fetching code + source files: 7750it [1:52:41,  3.33s/it]

Saved batch of 46 entries.

Fetching code + source files: 7761it [1:52:44,  2.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/http/src/org/apache/axis2/transport/http/AxisServlet.java (status: 404)
Warning: Failed to fetch file for ID 9571
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/http/src/org/apache/axis2/transport/http/AxisServlet.java (status: 404)
Warning: Failed to fetch file for ID 9572

Fetching code + source files: 7769it [1:52:46,  3.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CLabel.java (status: 404)
Warning: Failed to fetch file for ID 9579
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CLabel.java (status: 404)
Warning: Failed to fetch file for ID 9580

Fetching code + source files: 7800it [1:53:09,  3.79s/it]

Saved batch of 46 entries.

Fetching code + source files: 7802it [1:53:10,  2.24s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/presentations/AbstractTableInformationControl.java (status: 404)
Warning: Failed to fetch file for ID 9611
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/presentations/AbstractTableInformationControl.java (status: 404)
Warning: Failed to fetch file for ID 9612

Fetching code + source files: 7806it [1:53:11,  1.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/FileFormat.java (status: 404)
Warning: Failed to fetch file for ID 9615
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/FileFormat.java (status: 404)
Warning: Failed to fetch file for ID 9616

Fetching code + source files: 7835it [1:53:18,  4.71it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/reflog/ReflogItem.java (status: 404)
Warning: Failed to fetch file for ID 9645
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/reflog/ReflogItem.java (status: 404)
Warning: Failed to fetch file for ID 9646

Fetching code + source files: 7850it [1:53:38,  3.47s/it]

Saved batch of 44 entries.

Fetching code + source files: 7869it [1:53:43,  3.74it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Resource.java (status: 404)
Warning: Failed to fetch file for ID 9687
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Resource.java (status: 404)
Warning: Failed to fetch file for ID 9688

Fetching code + source files: 7891it [1:53:48,  4.14it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/deployment/resolver/AARFileBasedURIResolver.java (status: 404)
Warning: Failed to fetch file for ID 9711
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/deployment/resolver/AARFileBasedURIResolver.java (status: 404)
Warning: Failed to fetch file for ID 9712

Fetching code + source files: 7900it [1:54:05,  4.69s/it]

Saved batch of 46 entries.

Fetching code + source files: 7929it [1:54:12,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/accessibility/CTable.java (status: 404)
Warning: Failed to fetch file for ID 9755
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/accessibility/CTable.java (status: 404)
Warning: Failed to fetch file for ID 9756

Fetching code + source files: 7940it [1:54:15,  4.47it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/EvaluationOfEventProperties.java (status: 404)
Warning: Failed to fetch file for ID 9765
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/EvaluationOfEventProperties.java (status: 404)
Warning: Failed to fetch file for ID 9766

Fetching code + source files: 7949it [1:54:17,  3.86it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.launching/src/org/eclipse/dltk/launching/ScriptLaunchUtil.java (status: 404)
Warning: Failed to fetch file for ID 9777
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.launching/src/org/eclipse/dltk/launching/ScriptLaunchUtil.java (status: 404)
Warning: Failed to fetch file for ID 9778

Fetching code + source files: 7950it [1:54:34,  4.31s/it]

Saved batch of 44 entries.

Fetching code + source files: 7963it [1:54:37,  2.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 9791
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 9792

Fetching code + source files: 7983it [1:54:42,  4.25it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug491167_TableCursorScrolling.java (status: 404)
Warning: Failed to fetch file for ID 9811
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug491167_TableCursorScrolling.java (status: 404)
Warning: Failed to fetch file for ID 9812

Fetching code + source files: 7989it [1:54:43,  4.23it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/EditorDescriptor.java (status: 404)
Warning: Failed to fetch file for ID 9817
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/EditorDescriptor.java (status: 404)
Warning: Failed to fetch file for ID 9818

Fetching code + source files: 8000it [1:55:03,  3.66s/it]

Saved batch of 44 entries.

Fetching code + source files: 8048it [1:55:14,  4.90it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.ui.tests/src/org/eclipse/dltk/ui/tests/StringAsserts.java (status: 404)
Warning: Failed to fetch file for ID 9889
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.ui.tests/src/org/eclipse/dltk/ui/tests/StringAsserts.java (status: 404)
Warning: Failed to fetch file for ID 9890

Fetching code + source files: 8050it [1:55:31,  5.07s/it]

Saved batch of 48 entries.

Fetching code + source files: 8067it [1:55:36,  3.35it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/commands/NotHandledException.java (status: 404)
Warning: Failed to fetch file for ID 9911
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/commands/NotHandledException.java (status: 404)
Warning: Failed to fetch file for ID 9912

Fetching code + source files: 8072it [1:55:37,  4.14it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/ui/views/evalDataTable/EvalTableContentProvider.java (status: 404)
Warning: Failed to fetch file for ID 9915
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/ui/views/evalDataTable/EvalTableContentProvider.java (status: 404)
Warning: Failed to fetch file for ID 9916

Fetching code + source files: 8075it [1:55:38,  3.79it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.core.tests/src/org/eclipse/dltk/core/tests/util/ModelTestUtils.java (status: 404)
Warning: Failed to fetch file for ID 9919
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.core.tests/src/org/eclipse/dltk/core/tests/util/ModelTestUtils.java (status: 404)
Warning: Failed to fetch file for ID 9920

Fetching code + source files: 8080it [1:55:39,  4.86it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/webservices-xmlschema/f189e891c88298f52f92cfe8f24dccb809e05607/xmlschema-walker/src/main/java/org/apache/ws/commons/schema/docpath/XmlSchemaPathFinder.java (status: 404)
Warning: Failed to fetch file for ID 9923
Failed to fetch file: https://raw.githubusercontent.com/apache/webservices-xmlschema/f189e891c88298f52f92cfe8f24dccb809e05607/xmlschema-walker/src/main/java/org/apache/ws/commons/schema/docpath/XmlSchemaPathFinder.java (status: 404)
Warning: Failed to fetch file for ID 9924

Fetching code + source files: 8089it [1:55:41,  4.15it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/GDK.java (status: 404)
Warning: Failed to fetch file for ID 9933
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/GDK.java (status: 404)
Warning: Failed to fetch file for ID 9934

Fetching code + source files: 8099it [1:55:43,  4.30it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/callhierarchy/LocationLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 9947
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/callhierarchy/LocationLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 9948

Fetching code + source files: 8100it [1:55:59,  4.12s/it]

Saved batch of 38 entries.

Fetching code + source files: 8116it [1:56:03,  3.80it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/di/DIUtils.java (status: 404)
Warning: Failed to fetch file for ID 9967
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/di/DIUtils.java (status: 404)
Warning: Failed to fetch file for ID 9968

Fetching code + source files: 8117it [1:56:03,  3.76it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.jface.databinding/src/org/eclipse/jface/internal/databinding/swt/ControlTooltipTextProperty.java (status: 404)
Warning: Failed to fetch file for ID 9969

Fetching code + source files: 8118it [1:56:04,  3.95it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.jface.databinding/src/org/eclipse/jface/internal/databinding/swt/ControlTooltipTextProperty.java (status: 404)
Warning: Failed to fetch file for ID 9970

Fetching code + source files: 8135it [1:56:08,  4.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.integration.tests/src/org/eclipse/linuxtools/docker/integration/tests/mock/MockConsoleView.java (status: 404)
Warning: Failed to fetch file for ID 9995
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.integration.tests/src/org/eclipse/linuxtools/docker/integration/tests/mock/MockConsoleView.java (status: 404)
Warning: Failed to fetch file for ID 9996

Fetching code + source files: 8150it [1:56:28,  4.11s/it]

Saved batch of 44 entries.

Fetching code + source files: 8155it [1:56:29,  1.14s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/transport/WalkEncryption.java (status: 404)
Warning: Failed to fetch file for ID 10021
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/transport/WalkEncryption.java (status: 404)
Warning: Failed to fetch file for ID 10022

Fetching code + source files: 8157it [1:56:30,  1.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/parsers/token/EOR.java (status: 404)
Warning: Failed to fetch file for ID 10023
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/parsers/token/EOR.java (status: 404)
Warning: Failed to fetch file for ID 10024

Fetching code + source files: 8200it [1:56:57,  3.36s/it]

Saved batch of 46 entries.

Fetching code + source files: 8238it [1:57:05,  5.01it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/keys/model/BindingModel.java (status: 404)
Warning: Failed to fetch file for ID 10116
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/keys/model/BindingModel.java (status: 404)
Warning: Failed to fetch file for ID 10118

Fetching code + source files: 8247it [1:57:08,  4.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/fieldassist/ContentProposalAdapter.java (status: 404)
Warning: Failed to fetch file for ID 10127
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/fieldassist/ContentProposalAdapter.java (status: 404)
Warning: Failed to fetch file for ID 10128

Fetching code + source files: 8250it [1:57:24,  3.70s/it]

Saved batch of 46 entries.

Fetching code + source files: 8269it [1:57:29,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/builder/unknowncontent/InputStreamDataSource.java (status: 404)
Warning: Failed to fetch file for ID 10155
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/builder/unknowncontent/InputStreamDataSource.java (status: 404)
Warning: Failed to fetch file for ID 10156

Fetching code + source files: 8275it [1:57:30,  4.80it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 10161
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 10162

Fetching code + source files: 8300it [1:57:52,  3.44s/it]

Saved batch of 46 entries.

Fetching code + source files: 8305it [1:57:53,  1.28s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 10201
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 10202

Fetching code + source files: 8307it [1:57:54,  1.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/PackWriter.java (status: 404)
Warning: Failed to fetch file for ID 10203
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/PackWriter.java (status: 404)
Warning: Failed to fetch file for ID 10204

Fetching code + source files: 8309it [1:57:54,  1.47it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/CustomizePerspectiveDialog.java (status: 404)
Warning: Failed to fetch file for ID 10211
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/CustomizePerspectiveDialog.java (status: 404)
Warning: Failed to fetch file for ID 10212

Fetching code + source files: 8321it [1:57:56,  5.02it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/keys/model/BindingModel.java (status: 404)
Warning: Failed to fetch file for ID 10225
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/keys/model/BindingModel.java (status: 404)
Warning: Failed to fetch file for ID 10226

Fetching code + source files: 8338it [1:58:00,  5.27it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java (status: 404)
Warning: Failed to fetch file for ID 10241
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java (status: 404)
Warning: Failed to fetch file for ID 10242

Fetching code + source files: 8350it [1:58:19,  4.75s/it]

Saved batch of 40 entries.

Fetching code + source files: 8369it [1:58:24,  3.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyOuterKeylineSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 10275
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyOuterKeylineSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 10276

Fetching code + source files: 8402it [1:58:47,  2.48s/it]

Saved batch of 48 entries.

Fetching code + source files: 8404it [1:58:48,  1.55s/it]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 10315
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 10316

Fetching code + source files: 8416it [1:58:51,  3.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.launch/src/org/eclipse/linuxtools/internal/valgrind/launch/ValgrindOptionsTab.java (status: 404)
Warning: Failed to fetch file for ID 10327
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.launch/src/org/eclipse/linuxtools/internal/valgrind/launch/ValgrindOptionsTab.java (status: 404)
Warning: Failed to fetch file for ID 10328

Fetching code + source files: 8419it [1:58:52,  3.81it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/Snippet031TableViewerCustomTooltipsMultiSelection.java (status: 404)
Warning: Failed to fetch file for ID 10331
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/Snippet031TableViewerCustomTooltipsMultiSelection.java (status: 404)
Warning: Failed to fetch file for ID 10332

Fetching code + source files: 8433it [1:58:55,  4.00it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/WorkbenchPreferenceExtensionNode.java (status: 404)
Warning: Failed to fetch file for ID 10347
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/WorkbenchPreferenceExtensionNode.java (status: 404)
Warning: Failed to fetch file for ID 10348

Fetching code + source files: 8450it [1:59:16,  3.40s/it]

Saved batch of 42 entries.

Fetching code + source files: 8501it [1:59:44,  2.64s/it]

Saved batch of 50 entries.

Fetching code + source files: 8519it [1:59:48,  3.90it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 10451
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 10452

Fetching code + source files: 8529it [1:59:50,  4.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IViewReference.java (status: 404)
Warning: Failed to fetch file for ID 10463
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IViewReference.java (status: 404)
Warning: Failed to fetch file for ID 10464

Fetching code + source files: 8541it [1:59:53,  4.87it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 10473
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 10474

Fetching code + source files: 8551it [2:00:11,  2.79s/it]

Saved batch of 44 entries.

Fetching code + source files: 8571it [2:00:15,  4.27it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 10509
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 10510

Fetching code + source files: 8577it [2:00:16,  4.82it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/util/AbstractCssTraverser.java (status: 404)
Warning: Failed to fetch file for ID 10515
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/util/AbstractCssTraverser.java (status: 404)
Warning: Failed to fetch file for ID 10516

Fetching code + source files: 8580it [2:00:17,  5.33it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 10517
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 10518

Fetching code + source files: 8600it [2:00:38,  4.48s/it]

Saved batch of 44 entries.

Fetching code + source files: 8603it [2:00:39,  1.97s/it]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 10547
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 10548

Fetching code + source files: 8614it [2:00:41,  3.62it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/transport/sshd/SshdSession.java (status: 404)
Warning: Failed to fetch file for ID 10561
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/transport/sshd/SshdSession.java (status: 404)
Warning: Failed to fetch file for ID 10562

Fetching code + source files: 8619it [2:00:42,  5.26it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 10567

Fetching code + source files: 8621it [2:00:42,  5.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 10568

Fetching code + source files: 8624it [2:00:43,  5.42it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/MarkerHandler.java (status: 404)
Warning: Failed to fetch file for ID 10571
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/MarkerHandler.java (status: 404)
Warning: Failed to fetch file for ID 10572

Fetching code + source files: 8636it [2:00:45,  5.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/util/CommandLineOption.java (status: 404)
Warning: Failed to fetch file for ID 10585
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/util/CommandLineOption.java (status: 404)
Warning: Failed to fetch file for ID 10586

Fetching code + source files: 8650it [2:01:05,  4.41s/it]

Saved batch of 40 entries.

Fetching code + source files: 8668it [2:01:09,  4.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT OpenGL/common/org/eclipse/swt/opengl/GLData.java (status: 404)
Warning: Failed to fetch file for ID 10629
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT OpenGL/common/org/eclipse/swt/opengl/GLData.java (status: 404)
Warning: Failed to fetch file for ID 10630

Fetching code + source files: 8679it [2:01:12,  4.62it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/dialogs/ViewerFileFilter.java (status: 404)
Warning: Failed to fetch file for ID 10645
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/dialogs/ViewerFileFilter.java (status: 404)
Warning: Failed to fetch file for ID 10646

Fetching code + source files: 8690it [2:01:14,  5.00it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 10655
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 10656

Fetching code + source files: 8700it [2:01:35,  4.72s/it]

Saved batch of 44 entries.

Fetching code + source files: 8701it [2:01:35,  3.57s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/ToolBar.java (status: 404)
Warning: Failed to fetch file for ID 10669
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/ToolBar.java (status: 404)
Warning: Failed to fetch file for ID 10670

Fetching code + source files: 8750it [2:02:03,  3.40s/it]

Saved batch of 48 entries.

Fetching code + source files: 8752it [2:02:04,  2.18s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 10725
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 10726

Fetching code + source files: 8788it [2:02:12,  4.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet305.java (status: 404)
Warning: Failed to fetch file for ID 10767
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet305.java (status: 404)
Warning: Failed to fetch file for ID 10768

Fetching code + source files: 8793it [2:02:13,  4.42it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 10773
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 10774

Fetching code + source files: 8801it [2:02:31,  2.99s/it]

Saved batch of 44 entries.

Fetching code + source files: 8812it [2:02:33,  2.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/cde/ui/DocumentTableLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 10797
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/cde/ui/DocumentTableLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 10798

Fetching code + source files: 8832it [2:02:38,  4.80it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/transport/sshd/SshdSession.java (status: 404)
Warning: Failed to fetch file for ID 10823
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.ssh.apache/src/org/eclipse/jgit/transport/sshd/SshdSession.java (status: 404)
Warning: Failed to fetch file for ID 10824

Fetching code + source files: 8845it [2:02:40,  6.32it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/ConnectionMessages.java (status: 404)
Warning: Failed to fetch file for ID 10835
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/ConnectionMessages.java (status: 404)
Warning: Failed to fetch file for ID 10836

Fetching code + source files: 8851it [2:02:59,  3.35s/it]

Saved batch of 44 entries.

Fetching code + source files: 8862it [2:03:02,  3.03it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/dialogs/DeprecatedUIWizardsAuto.java (status: 404)
Warning: Failed to fetch file for ID 10856
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/dialogs/DeprecatedUIWizardsAuto.java (status: 404)
Warning: Failed to fetch file for ID 10857

Fetching code + source files: 8878it [2:03:06,  4.59it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 10878
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 10879

Fetching code + source files: 8892it [2:03:09,  5.35it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/ViewerTestDTD.java (status: 404)
Warning: Failed to fetch file for ID 10894
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/ViewerTestDTD.java (status: 404)
Warning: Failed to fetch file for ID 10895

Fetching code + source files: 8901it [2:03:28,  3.40s/it]

Saved batch of 44 entries.

Fetching code + source files: 8922it [2:03:32,  4.25it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/core/search/SearchPattern.java (status: 404)
Warning: Failed to fetch file for ID 10930
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.core/search/org/eclipse/dltk/core/search/SearchPattern.java (status: 404)
Warning: Failed to fetch file for ID 10931

Fetching code + source files: 8951it [2:03:55,  3.73s/it]

Saved batch of 48 entries.

Fetching code + source files: 9000it [2:04:25,  5.59s/it]

Saved batch of 50 entries.

Fetching code + source files: 9002it [2:04:25,  2.92s/it]

Reached 4500 requests, sleeping for 1 hour ...

Fetching code + source files: 9018it [3:04:29, 30.71s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 11042
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 11043

Fetching code + source files: 9034it [3:04:33,  1.15s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 11060
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 11061

Fetching code + source files: 9045it [3:04:35,  3.16it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.core.tests/src/org/eclipse/dltk/core/tests/ProjectSetup.java (status: 404)
Warning: Failed to fetch file for ID 11070
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/tests/org.eclipse.dltk.core.tests/src/org/eclipse/dltk/core/tests/ProjectSetup.java (status: 404)
Warning: Failed to fetch file for ID 11071

Fetching code + source files: 9051it [3:04:54,  3.59s/it]

Saved batch of 44 entries.

Fetching code + source files: 9067it [3:04:58,  3.75it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/css2/CSSPropertyFontSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 11098
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/css2/CSSPropertyFontSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 11099

Fetching code + source files: 9101it [3:05:23,  3.18s/it]

Saved batch of 48 entries.

Fetching code + source files: 9105it [3:05:24,  1.03s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 11140
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 11141

Fetching code + source files: 9108it [3:05:26,  1.46it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 11144
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 11145

Fetching code + source files: 9150it [3:05:53,  3.38s/it]

Saved batch of 46 entries.

Fetching code + source files: 9152it [3:05:54,  2.28s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java (status: 404)
Warning: Failed to fetch file for ID 11194
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java (status: 404)
Warning: Failed to fetch file for ID 11195

Fetching code + source files: 9186it [3:06:02,  3.23it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 11234
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/DebugConsoleManager.java (status: 404)
Warning: Failed to fetch file for ID 11235

Fetching code + source files: 9197it [3:06:05,  4.54it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 11246
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 11247

Fetching code + source files: 9201it [3:06:23,  3.42s/it]

Saved batch of 44 entries.

Fetching code + source files: 9214it [3:06:26,  2.52it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/ViewerTestDTD.java (status: 404)
Warning: Failed to fetch file for ID 11266
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/tests/org.eclipse.wst.dtd.ui.tests/src/org/eclipse/wst/dtd/ui/tests/viewer/ViewerTestDTD.java (status: 404)
Warning: Failed to fetch file for ID 11267

Fetching code + source files: 9224it [3:06:29,  3.93it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 11280
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 11281

Fetching code + source files: 9227it [3:06:30,  4.43it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/action/TrimAction.java (status: 404)
Warning: Failed to fetch file for ID 11286
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-core/src/main/java/org/apache/uima/ruta/action/TrimAction.java (status: 404)
Warning: Failed to fetch file for ID 11287

Fetching code + source files: 9236it [3:06:32,  3.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.integration.tests/src/org/eclipse/linuxtools/docker/integration/tests/mock/MockConsoleView.java (status: 404)
Warning: Failed to fetch file for ID 11296
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.integration.tests/src/org/eclipse/linuxtools/docker/integration/tests/mock/MockConsoleView.java (status: 404)
Warning: Failed to fetch file for ID 11297

Fetching code + source files: 9248it [3:06:36,  3.90it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/ConnectionMessages.java (status: 404)
Warning: Failed to fetch file for ID 11310
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/client/ConnectionMessages.java (status: 404)
Warning: Failed to fetch file for ID 11311

Fetching code + source files: 9251it [3:06:53,  2.84s/it]

Saved batch of 40 entries.

Fetching code + source files: 9260it [3:06:56,  1.87it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 11324
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 11325

Fetching code + source files: 9301it [3:07:25,  2.58s/it]

Saved batch of 48 entries.

Fetching code + source files: 9314it [3:07:28,  3.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/AbstractPartSelectionTracker.java (status: 404)
Warning: Failed to fetch file for ID 11398
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/AbstractPartSelectionTracker.java (status: 404)
Warning: Failed to fetch file for ID 11399

Fetching code + source files: 9324it [3:07:30,  3.91it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 11410
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/bindings/src/main/java/org/apache/wss4j/binding/wsu10/TimestampType.java (status: 404)
Warning: Failed to fetch file for ID 11411

Fetching code + source files: 9342it [3:07:34,  4.76it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/impl/dom/CSSValueListImpl.java (status: 404)
Warning: Failed to fetch file for ID 11432
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/impl/dom/CSSValueListImpl.java (status: 404)
Warning: Failed to fetch file for ID 11433

Fetching code + source files: 9350it [3:07:54,  3.59s/it]

Saved batch of 44 entries.

Fetching code + source files: 9358it [3:07:56,  1.38it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT OpenGL/common/org/eclipse/swt/opengl/GLData.java (status: 404)
Warning: Failed to fetch file for ID 11452
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT OpenGL/common/org/eclipse/swt/opengl/GLData.java (status: 404)
Warning: Failed to fetch file for ID 11453

Fetching code + source files: 9366it [3:07:59,  2.96it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/adapters/XSDWildcardAdapter.java (status: 404)
Warning: Failed to fetch file for ID 11460
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xsd.ui/src-adt-xsd/org/eclipse/wst/xsd/ui/internal/adapters/XSDWildcardAdapter.java (status: 404)
Warning: Failed to fetch file for ID 11461

Fetching code + source files: 9384it [3:08:04,  2.99it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/dialogs/ComboObjectEditor.java (status: 404)
Warning: Failed to fetch file for ID 11484
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/dialogs/ComboObjectEditor.java (status: 404)
Warning: Failed to fetch file for ID 11485

Fetching code + source files: 9392it [3:08:06,  4.01it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 11492
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 11493

Fetching code + source files: 9401it [3:08:25,  3.27s/it]

Saved batch of 42 entries.

Fetching code + source files: 9437it [3:08:34,  4.59it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/preferences/dialogs/CreateStepFilterDialog.java (status: 404)
Warning: Failed to fetch file for ID 11540
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/preferences/dialogs/CreateStepFilterDialog.java (status: 404)
Warning: Failed to fetch file for ID 11541

Fetching code + source files: 9451it [3:08:54,  2.81s/it]

Saved batch of 48 entries.

Fetching code + source files: 9462it [3:08:57,  2.52it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet305.java (status: 404)
Warning: Failed to fetch file for ID 11576
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet305.java (status: 404)
Warning: Failed to fetch file for ID 11577

Fetching code + source files: 9472it [3:08:59,  4.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/theme/css/NullElementSelector.java (status: 404)
Warning: Failed to fetch file for ID 11588
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/theme/css/NullElementSelector.java (status: 404)
Warning: Failed to fetch file for ID 11589

Fetching code + source files: 9479it [3:09:01,  4.91it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/ToolBar.java (status: 404)
Warning: Failed to fetch file for ID 11596
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/ToolBar.java (status: 404)
Warning: Failed to fetch file for ID 11597

Fetching code + source files: 9501it [3:09:24,  3.53s/it]

Saved batch of 44 entries.

Fetching code + source files: 9509it [3:09:25,  2.00it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/pipeline/GenerateSentenceBIODescriptors.java (status: 404)
Warning: Failed to fetch file for ID 11630
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/pipeline/GenerateSentenceBIODescriptors.java (status: 404)
Warning: Failed to fetch file for ID 11631

Fetching code + source files: 9524it [3:09:29,  4.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 11646
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 11647

Fetching code + source files: 9527it [3:09:29,  4.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/SSEUIMessages.java (status: 404)
Warning: Failed to fetch file for ID 11650
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/SSEUIMessages.java (status: 404)
Warning: Failed to fetch file for ID 11651

Fetching code + source files: 9532it [3:09:30,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/CustomizePerspectiveDialog.java (status: 404)
Warning: Failed to fetch file for ID 11660
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/CustomizePerspectiveDialog.java (status: 404)
Warning: Failed to fetch file for ID 11661

Fetching code + source files: 9540it [3:09:32,  4.27it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.core/src/org/eclipse/wst/xsl/core/internal/validation/XSLValidationMessage.java (status: 404)
Warning: Failed to fetch file for ID 11668
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.core/src/org/eclipse/wst/xsl/core/internal/validation/XSLValidationMessage.java (status: 404)
Warning: Failed to fetch file for ID 11669

Fetching code + source files: 9543it [3:09:33,  4.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.core/DevTimeSupport/HeadParsers/XML10Names/XML10Names.java (status: 404)
Warning: Failed to fetch file for ID 11670
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.core/DevTimeSupport/HeadParsers/XML10Names/XML10Names.java (status: 404)
Warning: Failed to fetch file for ID 11671

Fetching code + source files: 9551it [3:09:53,  3.64s/it]

Saved batch of 38 entries.

Fetching code + source files: 9571it [3:09:58,  4.37it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/FileTransport.java (status: 404)
Warning: Failed to fetch file for ID 11704
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/FileTransport.java (status: 404)
Warning: Failed to fetch file for ID 11705

Fetching code + source files: 9575it [3:09:59,  5.14it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/progress/AnimationManager.java (status: 404)
Warning: Failed to fetch file for ID 11708
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/progress/AnimationManager.java (status: 404)
Warning: Failed to fetch file for ID 11709

Fetching code + source files: 9587it [3:10:02,  4.50it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 11722
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 11723

Fetching code + source files: 9601it [3:10:24,  2.74s/it]

Saved batch of 44 entries.

Fetching code + source files: 9608it [3:10:25,  1.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/WWinPartService.java (status: 404)
Warning: Failed to fetch file for ID 11758
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/WWinPartService.java (status: 404)
Warning: Failed to fetch file for ID 11759

Fetching code + source files: 9610it [3:10:26,  2.05it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/EvaluationOfEventProperties.java (status: 404)
Warning: Failed to fetch file for ID 11760
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/EvaluationOfEventProperties.java (status: 404)
Warning: Failed to fetch file for ID 11761

Fetching code + source files: 9635it [3:10:32,  4.53it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.browser/src/org/eclipse/ui/internal/browser/BusyIndicator.java (status: 404)
Warning: Failed to fetch file for ID 11786
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.browser/src/org/eclipse/ui/internal/browser/BusyIndicator.java (status: 404)
Warning: Failed to fetch file for ID 11787

Fetching code + source files: 9636it [3:10:33,  3.99it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IPluginContribution.java (status: 404)
Warning: Failed to fetch file for ID 11788
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IPluginContribution.java (status: 404)
Warning: Failed to fetch file for ID 11789

Fetching code + source files: 9651it [3:10:54,  3.09s/it]

Saved batch of 42 entries.

Fetching code + source files: 9654it [3:10:55,  1.52s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java (status: 404)
Warning: Failed to fetch file for ID 11806
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java (status: 404)
Warning: Failed to fetch file for ID 11807

Fetching code + source files: 9686it [3:11:03,  4.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-model/src/main/java/com/epam/dlab/util/CloudSettingsDeserializer.java (status: 404)
Warning: Failed to fetch file for ID 11838
Failed to fetch file: https://raw.githubusercontent.com/epam/DLab/34483ee52cf8b79c4e51a54c82171564e5b8d50a/services/dlab-model/src/main/java/com/epam/dlab/util/CloudSettingsDeserializer.java (status: 404)
Warning: Failed to fetch file for ID 11839

Fetching code + source files: 9700it [3:11:24,  3.87s/it]

Saved batch of 46 entries.

Fetching code + source files: 9712it [3:11:27,  2.47it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/ui refactoring/org/eclipse/dltk/internal/ui/refactoring/reorg/RenameRefactoringWizard.java (status: 404)
Warning: Failed to fetch file for ID 11868
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/ui refactoring/org/eclipse/dltk/internal/ui/refactoring/reorg/RenameRefactoringWizard.java (status: 404)
Warning: Failed to fetch file for ID 11869

Fetching code + source files: 9714it [3:11:27,  2.82it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/NeuralEventTimeRelationsEvaluation.java (status: 404)
Warning: Failed to fetch file for ID 11870
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/NeuralEventTimeRelationsEvaluation.java (status: 404)
Warning: Failed to fetch file for ID 11871

Fetching code + source files: 9746it [3:11:35,  4.70it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/preferences/GitDecoratorPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 11904
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/preferences/GitDecoratorPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 11905

Fetching code + source files: 9748it [3:11:35,  4.60it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust13.java (status: 404)
Warning: Failed to fetch file for ID 11908
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust13.java (status: 404)
Warning: Failed to fetch file for ID 11909

Fetching code + source files: 9751it [3:11:54,  2.55s/it]

Saved batch of 42 entries.

Fetching code + source files: 9770it [3:12:00,  4.41it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/menu/impl/HandledMenuItemImpl.java (status: 404)
Warning: Failed to fetch file for ID 11934
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/menu/impl/HandledMenuItemImpl.java (status: 404)
Warning: Failed to fetch file for ID 11935

Fetching code + source files: 9801it [3:12:25,  2.52s/it]

Saved batch of 48 entries.

Fetching code + source files: 9814it [3:12:28,  3.12it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IViewReference.java (status: 404)
Warning: Failed to fetch file for ID 11990
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IViewReference.java (status: 404)
Warning: Failed to fetch file for ID 11991

Fetching code + source files: 9818it [3:12:29,  3.84it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 11994
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 11995

Fetching code + source files: 9844it [3:12:35,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 12020
Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 12021

Fetching code + source files: 9848it [3:12:36,  4.17it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.model.edit/src/main/java/org/eclipse/m2e/model/edit/pom/impl/ReportSetImpl.java (status: 404)
Warning: Failed to fetch file for ID 12024
Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.model.edit/src/main/java/org/eclipse/m2e/model/edit/pom/impl/ReportSetImpl.java (status: 404)
Warning: Failed to fetch file for ID 12025

Fetching code + source files: 9850it [3:12:55,  3.71s/it]

Saved batch of 42 entries.

Fetching code + source files: 9876it [3:13:01,  4.09it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/WorkbenchPreferenceExtensionNode.java (status: 404)
Warning: Failed to fetch file for ID 12058

Fetching code + source files: 9877it [3:13:02,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/preferences/WorkbenchPreferenceExtensionNode.java (status: 404)
Warning: Failed to fetch file for ID 12059

Fetching code + source files: 9901it [3:13:25,  3.41s/it]

Saved batch of 48 entries.

Fetching code + source files: 9938it [3:13:35,  4.30it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/readers/SequentialLogFileReader.java (status: 404)
Warning: Failed to fetch file for ID 12130
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/readers/SequentialLogFileReader.java (status: 404)
Warning: Failed to fetch file for ID 12131

Fetching code + source files: 9944it [3:13:36,  4.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/presentations/AbstractTableInformationControl.java (status: 404)
Warning: Failed to fetch file for ID 12136
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/presentations/AbstractTableInformationControl.java (status: 404)
Warning: Failed to fetch file for ID 12137

Fetching code + source files: 9951it [3:13:57,  3.14s/it]

Saved batch of 46 entries.

Fetching code + source files: 9983it [3:14:04,  5.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/activity/task/ServiceTaskFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 12176
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/activity/task/ServiceTaskFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 12177

Fetching code + source files: 10001it [3:14:28,  3.09s/it]

Saved batch of 48 entries.

Fetching code + source files: 10034it [3:14:37,  4.42it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/fieldassist/ContentProposalAdapter.java (status: 404)
Warning: Failed to fetch file for ID 12240
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.jface/src/org/eclipse/jface/fieldassist/ContentProposalAdapter.java (status: 404)
Warning: Failed to fetch file for ID 12241

Fetching code + source files: 10037it [3:14:37,  5.13it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/http/src/org/apache/axis2/transport/http/AxisServlet.java (status: 404)
Warning: Failed to fetch file for ID 12242
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/transport/http/src/org/apache/axis2/transport/http/AxisServlet.java (status: 404)
Warning: Failed to fetch file for ID 12243

Fetching code + source files: 10048it [3:14:40,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.launch/src/org/eclipse/linuxtools/internal/valgrind/launch/ValgrindOptionsTab.java (status: 404)
Warning: Failed to fetch file for ID 12256
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/valgrind/org.eclipse.linuxtools.valgrind.launch/src/org/eclipse/linuxtools/internal/valgrind/launch/ValgrindOptionsTab.java (status: 404)
Warning: Failed to fetch file for ID 12257
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 12258

Fetching code + source files: 10051it [3:14:59,  2.94s/it]

Saved batch of 43 entries.
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/property/tasks/MultiInstanceLoopCharacteristicsDetailComposite.java (status: 404)
Warning: Failed to fetch file for ID 12259

Fetching code + source files: 10061it [3:15:02,  2.25it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/function/ExtractToFunctionWizardParamsPage.java (status: 404)
Warning: Failed to fetch file for ID 12268
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/function/ExtractToFunctionWizardParamsPage.java (status: 404)
Warning: Failed to fetch file for ID 12269

Fetching code + source files: 10088it [3:15:09,  4.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/cde/ui/DocumentTableLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 12306
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/cde/ui/DocumentTableLabelProvider.java (status: 404)
Warning: Failed to fetch file for ID 12307

Fetching code + source files: 10093it [3:15:10,  4.87it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 12312
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 12313

Fetching code + source files: 10100it [3:15:31,  5.31s/it]

Saved batch of 43 entries.

Fetching code + source files: 10110it [3:15:33,  1.54it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/PackWriter.java (status: 404)
Warning: Failed to fetch file for ID 12336
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/pack/PackWriter.java (status: 404)
Warning: Failed to fetch file for ID 12337

Fetching code + source files: 10116it [3:15:35,  2.93it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/fillhandle/FillHandleLayerPainter.java (status: 404)
Warning: Failed to fetch file for ID 12344
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/fillhandle/FillHandleLayerPainter.java (status: 404)
Warning: Failed to fetch file for ID 12345

Fetching code + source files: 10127it [3:15:37,  4.90it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 12360
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 12361

Fetching code + source files: 10140it [3:15:40,  4.22it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 12374
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 12375

Fetching code + source files: 10143it [3:15:41,  5.05it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 12376
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/tcp/TCPSender.java (status: 404)
Warning: Failed to fetch file for ID 12377

Fetching code + source files: 10145it [3:15:41,  5.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests/src/org/eclipse/jface/widgets/TestUnitTextFactory.java (status: 404)
Warning: Failed to fetch file for ID 12378
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests/src/org/eclipse/jface/widgets/TestUnitTextFactory.java (status: 404)
Warning: Failed to fetch file for ID 12379

Fetching code + source files: 10151it [3:16:02,  3.48s/it]

Saved batch of 38 entries.

Fetching code + source files: 10154it [3:16:03,  1.52s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/css2/CSSPropertyFontSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 12388
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/css2/CSSPropertyFontSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 12389

Fetching code + source files: 10200it [3:16:33,  4.22s/it]

Saved batch of 48 entries.

Fetching code + source files: 10240it [3:16:42,  3.96it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 12492
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 12493

Fetching code + source files: 10243it [3:16:43,  4.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/property/JbpmIoParametersListComposite.java (status: 404)
Warning: Failed to fetch file for ID 12494
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.runtime.jboss.jbpm/src/org/eclipse/bpmn2/modeler/runtime/jboss/jbpm5/property/JbpmIoParametersListComposite.java (status: 404)
Warning: Failed to fetch file for ID 12495

Fetching code + source files: 10251it [3:17:04,  3.08s/it]

Saved batch of 46 entries.

Fetching code + source files: 10258it [3:17:06,  1.68it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 12512
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 12513

Fetching code + source files: 10298it [3:17:16,  4.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/IDLTKDebugUIPreferenceConstants.java (status: 404)
Warning: Failed to fetch file for ID 12560
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/IDLTKDebugUIPreferenceConstants.java (status: 404)
Warning: Failed to fetch file for ID 12561

Fetching code + source files: 10301it [3:17:36,  2.74s/it]

Saved batch of 46 entries.

Fetching code + source files: 10308it [3:17:38,  1.76it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ObjectContributorManager.java (status: 404)
Warning: Failed to fetch file for ID 12574
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/ObjectContributorManager.java (status: 404)
Warning: Failed to fetch file for ID 12575

Fetching code + source files: 10311it [3:17:38,  2.84it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 12576
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 12577

Fetching code + source files: 10313it [3:17:39,  3.40it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 12578
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 12579

Fetching code + source files: 10315it [3:17:39,  3.90it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/Snippet031TableViewerCustomTooltipsMultiSelection.java (status: 404)
Warning: Failed to fetch file for ID 12580
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/examples/org.eclipse.jface.snippets/Eclipse JFace Snippets/org/eclipse/jface/snippets/viewers/Snippet031TableViewerCustomTooltipsMultiSelection.java (status: 404)
Warning: Failed to fetch file for ID 12581

Fetching code + source files: 10328it [3:17:43,  4.21it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/commentelement/impl/BasicCommentElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 12594
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/commentelement/impl/BasicCommentElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 12595

Fetching code + source files: 10351it [3:18:08,  2.94s/it]

Saved batch of 40 entries.

Fetching code + source files: 10378it [3:18:14,  4.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs/src/org/eclipse/jgit/lfs/lib/Constants.java (status: 404)
Warning: Failed to fetch file for ID 12654
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs/src/org/eclipse/jgit/lfs/lib/Constants.java (status: 404)
Warning: Failed to fetch file for ID 12655

Fetching code + source files: 10401it [3:18:39,  3.39s/it]

Saved batch of 48 entries.

Fetching code + source files: 10412it [3:18:42,  2.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/di/DIUtils.java (status: 404)
Warning: Failed to fetch file for ID 12694
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/di/DIUtils.java (status: 404)
Warning: Failed to fetch file for ID 12695

Fetching code + source files: 10438it [3:18:49,  4.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.executor/src/org/eclipse/titan/executor/executors/mctr/cli/CliExecutor.java (status: 404)
Warning: Failed to fetch file for ID 12722
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.executor/src/org/eclipse/titan/executor/executors/mctr/cli/CliExecutor.java (status: 404)
Warning: Failed to fetch file for ID 12723

Fetching code + source files: 10450it [3:19:11,  3.84s/it]

Saved batch of 46 entries.

Fetching code + source files: 10467it [3:19:15,  3.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.regressiontests/src/org/eclipse/titan/regressiontests/designer/statictests/Basic_tests/AST_Syntax_warning_tests.java (status: 404)
Warning: Failed to fetch file for ID 12756
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.regressiontests/src/org/eclipse/titan/regressiontests/designer/statictests/Basic_tests/AST_Syntax_warning_tests.java (status: 404)
Warning: Failed to fetch file for ID 12757

Fetching code + source files: 10492it [3:19:22,  3.85it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/cleartk/SumContext.java (status: 404)
Warning: Failed to fetch file for ID 12786
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/cleartk/SumContext.java (status: 404)
Warning: Failed to fetch file for ID 12787

Fetching code + source files: 10495it [3:19:22,  4.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 12788
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 12789

Fetching code + source files: 10501it [3:19:43,  3.39s/it]

Saved batch of 44 entries.

Fetching code + source files: 10536it [3:19:50,  5.51it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/MarkerHandler.java (status: 404)
Warning: Failed to fetch file for ID 12830
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/MarkerHandler.java (status: 404)
Warning: Failed to fetch file for ID 12831

Fetching code + source files: 10540it [3:19:50,  5.16it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/util/CommandLineOption.java (status: 404)
Warning: Failed to fetch file for ID 12834
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/util/CommandLineOption.java (status: 404)
Warning: Failed to fetch file for ID 12835

Fetching code + source files: 10551it [3:20:13,  4.10s/it]

Saved batch of 46 entries.

Fetching code + source files: 10564it [3:20:16,  2.70it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.regressiontests/src/org/eclipse/titan/regressiontests/designer/statictests/Basic_tests/AST_Syntax_warning_tests.java (status: 404)
Warning: Failed to fetch file for ID 12858
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.regressiontests/src/org/eclipse/titan/regressiontests/designer/statictests/Basic_tests/AST_Syntax_warning_tests.java (status: 404)
Warning: Failed to fetch file for ID 12859

Fetching code + source files: 10574it [3:20:18,  5.10it/s]

Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 12870
Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 12871

Fetching code + source files: 10585it [3:20:20,  4.02it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/fillhandle/FillHandleLayerPainter.java (status: 404)
Warning: Failed to fetch file for ID 12881
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/fillhandle/FillHandleLayerPainter.java (status: 404)
Warning: Failed to fetch file for ID 12882

Fetching code + source files: 10600it [3:20:43,  4.27s/it]

Saved batch of 44 entries.

Fetching code + source files: 10618it [3:20:47,  4.67it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 12917
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 12918

Fetching code + source files: 10624it [3:20:48,  5.03it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.model.edit/src/main/java/org/eclipse/m2e/model/edit/pom/impl/ReportSetImpl.java (status: 404)
Warning: Failed to fetch file for ID 12923
Failed to fetch file: https://raw.githubusercontent.com/eclipse/m2e-core/7400bf563885fdf122aaccf356c398a0a9120ffa/org.eclipse.m2e.model.edit/src/main/java/org/eclipse/m2e/model/edit/pom/impl/ReportSetImpl.java (status: 404)
Warning: Failed to fetch file for ID 12924

Fetching code + source files: 10641it [3:20:51,  6.64it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug499850_VirtualTableHang.java (status: 404)
Warning: Failed to fetch file for ID 12943
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug499850_VirtualTableHang.java (status: 404)
Warning: Failed to fetch file for ID 12944

Fetching code + source files: 10651it [3:21:12,  3.78s/it]

Saved batch of 44 entries.

Fetching code + source files: 10700it [3:21:43,  4.83s/it]

Saved batch of 50 entries.

Fetching code + source files: 10713it [3:21:47,  2.95it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyOuterKeylineSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 13029
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyOuterKeylineSWTHandler.java (status: 404)
Warning: Failed to fetch file for ID 13030

Fetching code + source files: 10725it [3:21:50,  4.52it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 13041
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/internal/forms/widgets/FormUtil.java (status: 404)
Warning: Failed to fetch file for ID 13042

Fetching code + source files: 10741it [3:21:53,  4.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/commentelement/impl/BasicCommentElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 13057
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/commentelement/impl/BasicCommentElementHandler.java (status: 404)
Warning: Failed to fetch file for ID 13058

Fetching code + source files: 10750it [3:22:14,  4.75s/it]

Saved batch of 44 entries.

Fetching code + source files: 10759it [3:22:17,  1.77it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/progress/AnimationManager.java (status: 404)
Warning: Failed to fetch file for ID 13079
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/progress/AnimationManager.java (status: 404)
Warning: Failed to fetch file for ID 13080

Fetching code + source files: 10800it [3:22:45,  5.46s/it]

Saved batch of 48 entries.

Fetching code + source files: 10802it [3:22:46,  2.99s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/value/SimpleValueProperty.java (status: 404)
Warning: Failed to fetch file for ID 13125
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/value/SimpleValueProperty.java (status: 404)
Warning: Failed to fetch file for ID 13126

Fetching code + source files: 10804it [3:22:46,  1.60s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 13127
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 13128

Fetching code + source files: 10834it [3:22:53,  4.79it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/wsdl/SkeletonImpl.java (status: 404)
Warning: Failed to fetch file for ID 13163
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/wsdl/SkeletonImpl.java (status: 404)
Warning: Failed to fetch file for ID 13164

Fetching code + source files: 10850it [3:23:16,  4.94s/it]

Saved batch of 44 entries.

Fetching code + source files: 10851it [3:23:16,  3.74s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/function/ExtractToFunctionWizardParamsPage.java (status: 404)
Warning: Failed to fetch file for ID 13185

Fetching code + source files: 10852it [3:23:16,  2.79s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/function/ExtractToFunctionWizardParamsPage.java (status: 404)
Warning: Failed to fetch file for ID 13186

Fetching code + source files: 10869it [3:23:20,  4.63it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 13207
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 13208

Fetching code + source files: 10900it [3:23:46,  4.91s/it]

Saved batch of 46 entries.

Fetching code + source files: 10945it [3:23:56,  5.18it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.integration.tests/src/org/eclipse/linuxtools/docker/integration/tests/mock/MockConsoleView.java (status: 404)
Warning: Failed to fetch file for ID 13289
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/containers/org.eclipse.linuxtools.docker.integration.tests/src/org/eclipse/linuxtools/docker/integration/tests/mock/MockConsoleView.java (status: 404)
Warning: Failed to fetch file for ID 13290

Fetching code + source files: 10950it [3:24:18,  5.77s/it]

Saved batch of 48 entries.

Fetching code + source files: 10967it [3:24:22,  3.08it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/NeuralEventTimeRelationsEvaluation.java (status: 404)
Warning: Failed to fetch file for ID 13319
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/NeuralEventTimeRelationsEvaluation.java (status: 404)
Warning: Failed to fetch file for ID 13320

Fetching code + source files: 11000it [3:24:49,  5.21s/it]

Saved batch of 48 entries.

Fetching code + source files: 11003it [3:24:50,  2.19s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/Boolean_Type.java (status: 404)
Warning: Failed to fetch file for ID 13359
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/Boolean_Type.java (status: 404)
Warning: Failed to fetch file for ID 13360

Fetching code + source files: 11010it [3:24:51,  2.23it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 13365
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/MockEditorActionBarContributor.java (status: 404)
Warning: Failed to fetch file for ID 13366

Fetching code + source files: 11050it [3:25:19,  5.83s/it]

Saved batch of 46 entries.

Fetching code + source files: 11057it [3:25:21,  1.33it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs/src/org/eclipse/jgit/lfs/lib/Constants.java (status: 404)
Warning: Failed to fetch file for ID 13417
Failed to fetch file: https://raw.githubusercontent.com/eclipse/jgit/00523f38a19b073990239b0f837efa14197764c7/org.eclipse.jgit.lfs/src/org/eclipse/jgit/lfs/lib/Constants.java (status: 404)
Warning: Failed to fetch file for ID 13418

Fetching code + source files: 11062it [3:25:22,  3.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/DataAssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 13421
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/DataAssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 13422

Fetching code + source files: 11079it [3:25:26,  4.93it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/WorkbenchPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 13439
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/WorkbenchPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 13440

Fetching code + source files: 11082it [3:25:26,  5.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/pipeline/GenerateSentenceBIODescriptors.java (status: 404)
Warning: Failed to fetch file for ID 13441
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-core/src/main/java/org/apache/ctakes/core/pipeline/GenerateSentenceBIODescriptors.java (status: 404)
Warning: Failed to fetch file for ID 13442

Fetching code + source files: 11092it [3:25:29,  4.46it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 13453
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 13454

Fetching code + source files: 11100it [3:25:52,  4.82s/it]

Saved batch of 40 entries.

Fetching code + source files: 11107it [3:25:53,  1.24it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 13471
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/xsl/bundles/org.eclipse.wst.xsl.jaxp.debug/src/org/eclipse/wst/xsl/jaxp/debug/debugger/StyleFrame.java (status: 404)
Warning: Failed to fetch file for ID 13472

Fetching code + source files: 11150it [3:26:22,  4.06s/it]

Saved batch of 48 entries.

Fetching code + source files: 11179it [3:26:29,  4.59it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 13557
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/rpm/org.eclipse.linuxtools.rpm.ui.editor/src/org/eclipse/linuxtools/internal/rpm/ui/editor/preferences/PreferenceInitializer.java (status: 404)
Warning: Failed to fetch file for ID 13558

Fetching code + source files: 11185it [3:26:31,  3.74it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/ui refactoring/org/eclipse/dltk/internal/ui/refactoring/reorg/RenameRefactoringWizard.java (status: 404)
Warning: Failed to fetch file for ID 13563
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/ui refactoring/org/eclipse/dltk/internal/ui/refactoring/reorg/RenameRefactoringWizard.java (status: 404)
Warning: Failed to fetch file for ID 13564

Fetching code + source files: 11201it [3:26:56,  4.47s/it]

Saved batch of 46 entries.

Fetching code + source files: 11243it [3:27:05,  4.69it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 13637
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 13638

Fetching code + source files: 11248it [3:27:06,  5.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 13641
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 13642

Fetching code + source files: 11250it [3:27:27,  5.76s/it]

Saved batch of 46 entries.

Fetching code + source files: 11261it [3:27:30,  2.06it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/impl/dom/CSSValueListImpl.java (status: 404)
Warning: Failed to fetch file for ID 13655
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.css.core/src/org/eclipse/e4/ui/css/core/impl/dom/CSSValueListImpl.java (status: 404)
Warning: Failed to fetch file for ID 13656

Fetching code + source files: 11300it [3:28:00,  5.15s/it]

Saved batch of 48 entries.

Fetching code + source files: 11313it [3:28:03,  2.99it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/value/SimpleValueProperty.java (status: 404)
Warning: Failed to fetch file for ID 13713
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.core.databinding.property/src/org/eclipse/core/databinding/property/value/SimpleValueProperty.java (status: 404)
Warning: Failed to fetch file for ID 13714

Fetching code + source files: 11334it [3:28:07,  5.07it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/menu/impl/HandledMenuItemImpl.java (status: 404)
Warning: Failed to fetch file for ID 13737
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/bundles/org.eclipse.e4.ui.model.workbench/src/org/eclipse/e4/ui/model/application/ui/menu/impl/HandledMenuItemImpl.java (status: 404)
Warning: Failed to fetch file for ID 13738

Fetching code + source files: 11347it [3:28:11,  3.53it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/EvaluationOfEventProperties.java (status: 404)
Warning: Failed to fetch file for ID 13751
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/EvaluationOfEventProperties.java (status: 404)
Warning: Failed to fetch file for ID 13752

Fetching code + source files: 11350it [3:28:33,  4.95s/it]

Saved batch of 44 entries.

Fetching code + source files: 11353it [3:28:34,  2.22s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/data/ExtendedReflectiveColumnPropertyAccessor.java (status: 404)
Warning: Failed to fetch file for ID 13757
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.core/src/org/eclipse/nebula/widgets/nattable/data/ExtendedReflectiveColumnPropertyAccessor.java (status: 404)
Warning: Failed to fetch file for ID 13758

Fetching code + source files: 11369it [3:28:38,  3.82it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 13777
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 13778

Fetching code + source files: 11378it [3:28:40,  5.05it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/WorkbenchPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 13789
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/WorkbenchPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 13790

Fetching code + source files: 11390it [3:28:42,  5.55it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 13807
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 13808

Fetching code + source files: 11400it [3:29:05,  4.49s/it]

Saved batch of 42 entries.

Fetching code + source files: 11411it [3:29:07,  2.51it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 13829
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 13830

Fetching code + source files: 11443it [3:29:13,  4.59it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/presentations/AbstractTableInformationControl.java (status: 404)
Warning: Failed to fetch file for ID 13863
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/internal/presentations/AbstractTableInformationControl.java (status: 404)
Warning: Failed to fetch file for ID 13864

Fetching code + source files: 11450it [3:29:35,  4.77s/it]

Saved batch of 46 entries.

Fetching code + source files: 11453it [3:29:36,  2.16s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 13877
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.swt/bf870e8ff7e54069e96e5c9a74dc84d49a444484/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java (status: 404)
Warning: Failed to fetch file for ID 13878

Fetching code + source files: 11499it [3:29:47,  4.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 13929
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/TitanLoggerApi.java (status: 404)
Warning: Failed to fetch file for ID 13930

Fetching code + source files: 11500it [3:30:08,  6.31s/it]

Saved batch of 46 entries.

Fetching code + source files: 11533it [3:30:16,  4.28it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/DataAssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 13963
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/flow/DataAssociationFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 13964

Fetching code + source files: 11545it [3:30:18,  5.48it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 13973
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.runtime/src/org/eclipse/titan/runtime/core/Param_Types.java (status: 404)
Warning: Failed to fetch file for ID 13976

Fetching code + source files: 11550it [3:30:40,  4.93s/it]

Saved batch of 46 entries.

Fetching code + source files: 11597it [3:30:51,  5.37it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/dialogs/ComboObjectEditor.java (status: 404)
Warning: Failed to fetch file for ID 14039
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.core/src/org/eclipse/bpmn2/modeler/core/merrimac/dialogs/ComboObjectEditor.java (status: 404)
Warning: Failed to fetch file for ID 14040

Fetching code + source files: 11600it [3:31:12,  4.78s/it]

Saved batch of 48 entries.

Fetching code + source files: 11617it [3:31:16,  3.52it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 14067
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 14068

Fetching code + source files: 11621it [3:31:17,  3.83it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests/src/org/eclipse/jface/widgets/TestUnitTextFactory.java (status: 404)
Warning: Failed to fetch file for ID 14071
Failed to fetch file: https://raw.githubusercontent.com/eclipse/eclipse.platform.ui/e3bbb556534a1fb945e1036948325d14a8dd9c7a/tests/org.eclipse.jface.tests/src/org/eclipse/jface/widgets/TestUnitTextFactory.java (status: 404)
Warning: Failed to fetch file for ID 14072

Fetching code + source files: 11645it [3:31:22,  4.19it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/Boolean_Type.java (status: 404)
Warning: Failed to fetch file for ID 14097
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/types/Boolean_Type.java (status: 404)
Warning: Failed to fetch file for ID 14098

Fetching code + source files: 11650it [3:31:45,  5.59s/it]

Saved batch of 44 entries.

Fetching code + source files: 11701it [3:32:18,  3.58s/it]

Saved batch of 50 entries.

Fetching code + source files: 11710it [3:32:20,  1.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 14175
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/Location.java (status: 404)
Warning: Failed to fetch file for ID 14176

Fetching code + source files: 11719it [3:32:22,  3.77it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/IDLTKDebugUIPreferenceConstants.java (status: 404)
Warning: Failed to fetch file for ID 14187
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/IDLTKDebugUIPreferenceConstants.java (status: 404)
Warning: Failed to fetch file for ID 14188

Fetching code + source files: 11722it [3:32:23,  4.17it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 14189
Failed to fetch file: https://raw.githubusercontent.com/apache/ctakes/79be3ba2833857714bb301449f021cca36f373e6/ctakes-coreference/src/main/java/org/apache/ctakes/coreference/ae/features/cluster/MentionClusterStringFeaturesExtractor.java (status: 404)
Warning: Failed to fetch file for ID 14190

Fetching code + source files: 11750it [3:32:51,  5.83s/it]

Saved batch of 44 entries.

Fetching code + source files: 11769it [3:32:55,  3.91it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/readers/SequentialLogFileReader.java (status: 404)
Warning: Failed to fetch file for ID 14249
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.log.viewer/src/org/eclipse/titan/log/viewer/readers/SequentialLogFileReader.java (status: 404)
Warning: Failed to fetch file for ID 14250

Fetching code + source files: 11801it [3:33:24,  3.55s/it]

Saved batch of 48 entries.

Fetching code + source files: 11831it [3:33:31,  4.56it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 14319
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.designer/src/org/eclipse/titan/designer/AST/TTCN3/templates/Referenced_Template.java (status: 404)
Warning: Failed to fetch file for ID 14320

Fetching code + source files: 11841it [3:33:33,  5.22it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 14331
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.css.core/src/org/eclipse/wst/css/core/internal/document/CSSModelParser.java (status: 404)
Warning: Failed to fetch file for ID 14332

Fetching code + source files: 11850it [3:33:56,  5.36s/it]

Saved batch of 46 entries.

Fetching code + source files: 11866it [3:34:00,  3.77it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/builder/unknowncontent/InputStreamDataSource.java (status: 404)
Warning: Failed to fetch file for ID 14355
Failed to fetch file: https://raw.githubusercontent.com/apache/axis2-java/372582df483eb7991f85b6d0e765aec62339cdb7/modules/kernel/src/org/apache/axis2/builder/unknowncontent/InputStreamDataSource.java (status: 404)
Warning: Failed to fetch file for ID 14356

Fetching code + source files: 11900it [3:34:29,  6.13s/it]

Saved batch of 48 entries.

Fetching code + source files: 11903it [3:34:30,  2.45s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IPluginContribution.java (status: 404)
Warning: Failed to fetch file for ID 14411
Failed to fetch file: https://raw.githubusercontent.com/eclipse/rap/6295da95d01da6669c91bd4b058db9b89f35abaf/bundles/org.eclipse.rap.ui.workbench/Eclipse UI/org/eclipse/ui/IPluginContribution.java (status: 404)
Warning: Failed to fetch file for ID 14412

Fetching code + source files: 11931it [3:34:36,  5.00it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/preferences/GitDecoratorPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 14439
Failed to fetch file: https://raw.githubusercontent.com/eclipse/egit/45c1839348e50f1835a3f76e306af8d1a190d617/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/preferences/GitDecoratorPreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 14440

Fetching code + source files: 11947it [3:34:39,  4.94it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 14455
Failed to fetch file: https://raw.githubusercontent.com/apache/uima-ruta/08efb111a775b4ba01cf048ac699aa9c22188325/ruta-ep-addons/src/main/java/org/apache/uima/ruta/testing/evaluator/FeatureCasEvaluator.java (status: 404)
Warning: Failed to fetch file for ID 14456

Fetching code + source files: 11951it [3:35:02,  3.59s/it]

Saved batch of 44 entries.

Fetching code + source files: 11968it [3:35:06,  3.56it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.executor/src/org/eclipse/titan/executor/executors/mctr/cli/CliExecutor.java (status: 404)
Warning: Failed to fetch file for ID 14475
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titan.executor/src/org/eclipse/titan/executor/executors/mctr/cli/CliExecutor.java (status: 404)
Warning: Failed to fetch file for ID 14476

Fetching code + source files: 11989it [3:35:11,  4.66it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 14507
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 14508

Fetching code + source files: 11993it [3:35:12,  3.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/FileTransport.java (status: 404)
Warning: Failed to fetch file for ID 14511
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/transport-sample/src/main/java/samples/transport/FileTransport.java (status: 404)
Warning: Failed to fetch file for ID 14512

Fetching code + source files: 12000it [3:35:36,  5.29s/it]

Saved batch of 44 entries.

Fetching code + source files: 12009it [3:35:37,  1.82it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 14525
Failed to fetch file: https://raw.githubusercontent.com/eclipse/titan.EclipsePlug-ins/92bae808bfd4757c9a2f7cc0e59cd17ad801394c/org.eclipse.titanium.refactoring/src/org/eclipse/titanium/refactoring/fieldordering/ChangeCreator.java (status: 404)
Warning: Failed to fetch file for ID 14526

Fetching code + source files: 12051it [3:36:10,  3.25s/it]

Saved batch of 48 entries.

Fetching code + source files: 12060it [3:36:11,  2.31it/s]

Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 14590
Failed to fetch file: https://raw.githubusercontent.com/salesforce/Argus/121b59a268da264316cded6a3e9271366a23cd86/ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java (status: 404)
Warning: Failed to fetch file for ID 14591

Fetching code + source files: 12072it [3:36:14,  4.39it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/wsdl/SkeletonImpl.java (status: 404)
Warning: Failed to fetch file for ID 14606
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/axis-rt-core/src/main/java/org/apache/axis/wsdl/SkeletonImpl.java (status: 404)
Warning: Failed to fetch file for ID 14607

Fetching code + source files: 12097it [3:36:19,  5.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/SSEUIMessages.java (status: 404)
Warning: Failed to fetch file for ID 14636
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/core/bundles/org.eclipse.wst.sse.ui/src/org/eclipse/wst/sse/ui/internal/SSEUIMessages.java (status: 404)
Warning: Failed to fetch file for ID 14637

Fetching code + source files: 12100it [3:36:43,  6.55s/it]

Saved batch of 44 entries.

Fetching code + source files: 12151it [3:37:16,  3.60s/it]

Saved batch of 50 entries.

Fetching code + source files: 12166it [3:37:19,  3.49it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 14724
Failed to fetch file: https://raw.githubusercontent.com/eclipse/linuxtools/11865e6e7d86a9d2e63c7b25605f6055875e63ad/systemtap/org.eclipse.linuxtools.systemtap.ui.ide/src/org/eclipse/linuxtools/internal/systemtap/ui/ide/editors/stp/STPIndenter.java (status: 404)
Warning: Failed to fetch file for ID 14725

Fetching code + source files: 12201it [3:37:51,  4.01s/it]

Saved batch of 48 entries.

Fetching code + source files: 12206it [3:37:52,  1.17s/it]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/preferences/dialogs/CreateStepFilterDialog.java (status: 404)
Warning: Failed to fetch file for ID 14776
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.debug.ui/src/org/eclipse/dltk/debug/ui/preferences/dialogs/CreateStepFilterDialog.java (status: 404)
Warning: Failed to fetch file for ID 14777

Fetching code + source files: 12208it [3:37:53,  1.25it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.dataset/src/org/eclipse/nebula/widgets/nattable/dataset/generator/DataGenerator.java (status: 404)
Warning: Failed to fetch file for ID 14778
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.dataset/src/org/eclipse/nebula/widgets/nattable/dataset/generator/DataGenerator.java (status: 404)
Warning: Failed to fetch file for ID 14779

Fetching code + source files: 12251it [3:38:27,  4.83s/it]

Saved batch of 46 entries.

Fetching code + source files: 12285it [3:38:33,  7.03it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.dataset/src/org/eclipse/nebula/widgets/nattable/dataset/generator/DataGenerator.java (status: 404)
Warning: Failed to fetch file for ID 14862
Failed to fetch file: https://raw.githubusercontent.com/eclipse/nebula.widgets.nattable/02b4aba0e0b6998077b40e7d3f892743f7005023/org.eclipse.nebula.widgets.nattable.dataset/src/org/eclipse/nebula/widgets/nattable/dataset/generator/DataGenerator.java (status: 404)
Warning: Failed to fetch file for ID 14863

Fetching code + source files: 12298it [3:38:35,  5.11it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 14878
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 14879

Fetching code + source files: 12301it [3:38:59,  3.68s/it]

Saved batch of 46 entries.

Fetching code + source files: 12346it [3:39:08,  5.30it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 14940
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 14941

Fetching code + source files: 12349it [3:39:08,  5.57it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/activity/task/ServiceTaskFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 14942
Failed to fetch file: https://raw.githubusercontent.com/eclipse/bpmn2-modeler/fce8426d782272ee848251d954c98091bea0631c/plugins/org.eclipse.bpmn2.modeler.ui/src/org/eclipse/bpmn2/modeler/ui/features/activity/task/ServiceTaskFeatureContainer.java (status: 404)
Warning: Failed to fetch file for ID 14943

Fetching code + source files: 12351it [3:39:32,  4.24s/it]

Saved batch of 46 entries.

Fetching code + source files: 12380it [3:39:38,  4.97it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust13.java (status: 404)
Warning: Failed to fetch file for ID 14982
Failed to fetch file: https://raw.githubusercontent.com/apache/wss4j/5c2cbd7e7377296edab02ab79fc98b84fb47f825/policy/src/main/java/org/apache/wss4j/policy/model/Trust13.java (status: 404)
Warning: Failed to fetch file for ID 14983

Fetching code + source files: 12400it [3:40:06,  6.64s/it]

Saved batch of 48 entries.

Fetching code + source files: 12450it [3:40:39,  4.82s/it]

Saved batch of 50 entries.

Fetching code + source files: 12486it [3:40:48,  4.80it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 15093
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.jsdt.web.ui/src/org/eclipse/wst/jsdt/web/ui/actions/SimpleJSDTActionProxy.java (status: 404)
Warning: Failed to fetch file for ID 15094

Fetching code + source files: 12499it [3:40:50,  4.53it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 15111
Failed to fetch file: https://raw.githubusercontent.com/eclipse/webtools.sourceediting/fe6d03fa6ca31c9e5ebeba67b32f14d14335657d/web/bundles/org.eclipse.wst.html.ui/src/org/eclipse/wst/html/ui/internal/preferences/ui/HTMLSourcePreferencePage.java (status: 404)
Warning: Failed to fetch file for ID 15112

Fetching code + source files: 12501it [3:41:14,  4.39s/it]

Saved batch of 46 entries.

Fetching code + source files: 12550it [3:41:49,  5.58s/it]

Saved batch of 50 entries.

Fetching code + source files: 12601it [3:42:24,  4.14s/it]

Saved batch of 50 entries.

Fetching code + source files: 12624it [3:42:28,  5.78it/s]

Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 15251
Failed to fetch file: https://raw.githubusercontent.com/apache/axis1-java/7043f1ab0397d1ae35f879f2bcc99be1e9b55644/samples/integrationguide-sample/src/main/java/samples/integrationGuide/example2/MyEmitter.java (status: 404)
Warning: Failed to fetch file for ID 15252

Fetching code + source files: 12641it [3:42:31,  4.92it/s]

Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 15273
Failed to fetch file: https://raw.githubusercontent.com/eclipse/dltk.core/ff5ee79db0c2234347cb3f956de9b31047f43613/core/plugins/org.eclipse.dltk.ui/src/org/eclipse/dltk/internal/ui/wizards/buildpath/newsourcepage/BuildpathModifierQueries.java (status: 404)
Warning: Failed to fetch file for ID 15274

Fetching code + source files: 12651it [3:42:57,  5.03s/it]

Saved batch of 46 entries.

Fetching code + source files: 12701it [3:43:29,  5.24s/it]

Saved batch of 50 entries.

Fetching code + source files: 12710it [3:43:31,  1.06s/it]

Saved batch of 10 entries.
Completed JSON saving. Output: /home/marcelo/Doutorado/llm-code-review-on-smells/datasets/original_mlcq_samples.json
Saving CSV to: /home/marcelo/Doutorado/llm-code-review-on-smells/datasets/mlcq_samples_with_source_code.csv
CSV saved successfully.

=== Processing Summary ===
Total rows processed: 12710
Successfully processed: 11603
Skipped (fetch failures): 1107
Errors (parsing issues): 0
Skipped entries saved to: /home/marcelo/Doutorado/llm-code-review-on-smells/datasets/mlcq_samples_with_source_code_skipped.csv

## 3. CSV com source code

Após a coleta, o CSV gerado contém os snippets e o conteúdo completo do arquivo.

In [ ]:
with_source = pd.read_csv(BASE / "mlcq_enriched_dataset.csv")
with_source.head()

,id,repo_url,commit_hash,file_path,start_line,end_line,code_snippet,file_content,smell,severity,type,code_name
0,526,git@github.com:apache/syncope.git,114c412afbfba24ffb4fbc804e5308a823a16a78,/client/idrepo/ui/src/main/java/org/apache/syn...,35,37,private ConnIdSpecialName() {\n // ...,/*\n * Licensed to the Apache Software Foundat...,feature envy,none,function,org.apache.syncope.client.ui.commons.ConnIdSpe...
1,527,git@github.com:apache/syncope.git,114c412afbfba24ffb4fbc804e5308a823a16a78,/client/idrepo/ui/src/main/java/org/apache/syn...,35,37,private ConnIdSpecialName() {\n // ...,/*\n * Licensed to the Apache Software Foundat...,long method,none,function,org.apache.syncope.client.ui.commons.ConnIdSpe...
2,528,git@github.com:apache/tez.git,d5675c332497c1ac1dedefdf91e87476b5c0d7a9,/tez-runtime-library/src/main/java/org/apache/...,89,1427,public class UnorderedPartitionedKVWriter exte...,/**\n * Licensed to the Apache Software Founda...,blob,critical,class,org.apache.tez.runtime.library.common.writers....
3,529,git@github.com:apache/tez.git,d5675c332497c1ac1dedefdf91e87476b5c0d7a9,/tez-runtime-library/src/main/java/org/apache/...,89,1427,public class UnorderedPartitionedKVWriter exte...,/**\n * Licensed to the Apache Software Founda...,data class,critical,class,org.apache.tez.runtime.library.common.writers....
4,530,git@github.com:apache/tika.git,4131c6e30f2e0eb1feb85e0f7576531d4e830468,/tika-parsers/src/main/java/org/apache/tika/pa...,531,534,public String getImageMagickPath() {\n\n ...,/*\n * Licensed to the Apache Software Foundat...,feature envy,none,function,org.apache.tika.parser.ocr.TesseractOCRConfig#...

In [35]:
with_source.shape

(11603, 12)

## 4. Gerar SQL para a base de dados

Geração do arquivo de inserts a partir do CSV com source para inserção na base.

In [ ]:
# Inserts SQL já gerados; descomente abaixo para refazer
# import sys
# sys.path.insert(0, str(BASE / "database-storage"))
# from generate_sql_inserts_from_csv import generate_sql_inserts
#
# generate_sql_inserts(
#     input_csv=str(BASE / "mlcq_enriched_dataset.csv"),
#     output_sql=str(BASE / "mlcq_inserts.sql"),
# )